
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace craxx
{
    public static class actionData
    {
        public static ACTION_ITEM[] getACTION_ITEMCollection()
        {
            List<ACTION_ITEM> ret = new List<ACTION_ITEM>();
            ret.Add(new ACTION_ITEM { name = "クルクルパッ！", actioncode = "3point_landing" });
            ret.Add(new ACTION_ITEM { name = "ボールを投げる", actioncode = "ball2" });
            ret.Add(new ACTION_ITEM { name = "尻をつく", actioncode = "battle_hit" });
            ret.Add(new ACTION_ITEM { name = "ビッグフェイス", actioncode = "bigface_secret" });
            ret.Add(new ACTION_ITEM { name = "ジャンプして止まる", actioncode = "bubblegum" });
            ret.Add(new ACTION_ITEM { name = "大砲攻撃", actioncode = "cannon_attack" });
            ret.Add(new ACTION_ITEM { name = "巨人アクション", actioncode = "cannon_attack_run" });
            ret.Add(new ACTION_ITEM { name = "パーティスタート", actioncode = "channel_party_start" });
            ret.Add(new ACTION_ITEM { name = "ジャンプ座り", actioncode = "china_down" });
            ret.Add(new ACTION_ITEM { name = "構える", actioncode = "china_master_1" });
            ret.Add(new ACTION_ITEM { name = "中国のマスター 構え", actioncode = "china_master_2" });
            ret.Add(new ACTION_ITEM { name = "ライフル", actioncode = "commu_5th_rifle" });
            ret.Add(new ACTION_ITEM { name = "あけおめ", actioncode = "commu_akeome_1501" });
            ret.Add(new ACTION_ITEM { name = "グッピグプラカード（アクション小）", actioncode = "commu_ame_goodpigg_placard_1306" });
            ret.Add(new ACTION_ITEM { name = "お札パタパタ", actioncode = "commu_billfan_1502" });
            ret.Add(new ACTION_ITEM { name = "ビードダンス", actioncode = "commu_birddance_1606" });
            ret.Add(new ACTION_ITEM { name = "ボーリング", actioncode = "commu_bowling_1502" });
            ret.Add(new ACTION_ITEM { name = "バイバイ", actioncode = "commu_byebye" });
            ret.Add(new ACTION_ITEM { name = "百烈脚", actioncode = "commu_capcom_streetfighter_hyakuretsu_1504" });
            ret.Add(new ACTION_ITEM { name = "昇竜拳", actioncode = "commu_capcom_streetfighter_shoryuken_1504" });
            ret.Add(new ACTION_ITEM { name = "チョコ渡し", actioncode = "commu_chocoforyou_1502" });
            ret.Add(new ACTION_ITEM { name = "拍手", actioncode = "commu_clap" });
            ret.Add(new ACTION_ITEM { name = "どうぞどうぞ(ダチョウ倶楽部)", actioncode = "commu_dachokurabu_dozodozo_1307" });
            ret.Add(new ACTION_ITEM { name = "俺イヤだよ(ダチョウ倶楽部)", actioncode = "commu_dachokurabu_iyada_1307" });
            ret.Add(new ACTION_ITEM { name = "くるりんぱ(ダチョウ倶楽部)", actioncode = "commu_dachokurabu_kururinpa_1307" });
            ret.Add(new ACTION_ITEM { name = "じゃあ俺がやるよ(ダチョウ倶楽部)", actioncode = "commu_dachokurabu_oregayaru_1307" });
            ret.Add(new ACTION_ITEM { name = "訴えてやる！(ダチョウ倶楽部)", actioncode = "commu_dachokurabu_uttaeteyaru_1307" });
            ret.Add(new ACTION_ITEM { name = "喜んで★", actioncode = "commu_danceok" });
            ret.Add(new ACTION_ITEM { name = "ダンスウィズミー", actioncode = "commu_danceplease" });
            ret.Add(new ACTION_ITEM { name = "ドロン", actioncode = "commu_doron_tanuki_1511" });
            ret.Add(new ACTION_ITEM { name = "フリップ：ぷんぷん", actioncode = "commu_flip_angry_1306" });
            ret.Add(new ACTION_ITEM { name = "フリップ：激おこぷんぷん丸", actioncode = "commu_flip_gekioko_1306" });
            ret.Add(new ACTION_ITEM { name = "フリップ：やっほー", actioncode = "commu_flip_happy_1306" });
            ret.Add(new ACTION_ITEM { name = "フリップ：最近どう？", actioncode = "commu_flip_howareyou_1306" });
            ret.Add(new ACTION_ITEM { name = "かまちょ", actioncode = "commu_flip_kamacho_1404" });
            ret.Add(new ACTION_ITEM { name = "フリップ：ココだけの話", actioncode = "commu_flip_kokodake_1306" });
            ret.Add(new ACTION_ITEM { name = "フリップ：なごみ", actioncode = "commu_flip_mild_1306" });
            ret.Add(new ACTION_ITEM { name = "フリップ：おこなの？", actioncode = "commu_flip_oko_1306" });
            ret.Add(new ACTION_ITEM { name = "カンペ(イイネ！)", actioncode = "commu_flip_oko_good_1306" });
            ret.Add(new ACTION_ITEM { name = "カンペ(ワロタ)", actioncode = "commu_flip_oko_warota_1306" });
            ret.Add(new ACTION_ITEM { name = "フリップ：しょんぼり", actioncode = "commu_flip_sad_1306" });
            ret.Add(new ACTION_ITEM { name = "フリップ：ポカーン", actioncode = "commu_flip_surprise_1306" });
            ret.Add(new ACTION_ITEM { name = "ガオー", actioncode = "commu_gaoo_1410" });
            ret.Add(new ACTION_ITEM { name = "グッピグ立て看板", actioncode = "commu_goodpigg_billboard_1306" });
            ret.Add(new ACTION_ITEM { name = "グッピグダンス", actioncode = "commu_goodpigg_dance_1306" });
            ret.Add(new ACTION_ITEM { name = "グッピグプラカード（アクション大）", actioncode = "commu_goodpigg_placard_1306" });
            ret.Add(new ACTION_ITEM { name = "アイドルキメッ☆", actioncode = "commu_idolkime_1604" });
            ret.Add(new ACTION_ITEM { name = "6周年", actioncode = "commu_incentive_6th_1502" });
            ret.Add(new ACTION_ITEM { name = "祝★アメーバピグ７周年", actioncode = "commu_incentive_7th_1602" });
            ret.Add(new ACTION_ITEM { name = "ハート作るアクション", actioncode = "commu_incentive_heart_1508" });
            ret.Add(new ACTION_ITEM { name = "アイドルキメ", actioncode = "commu_incentive_kime_1506" });
            ret.Add(new ACTION_ITEM { name = "ラブアピール", actioncode = "commu_incentive_loveappeal_1503" });
            ret.Add(new ACTION_ITEM { name = "タオルぶんぶん", actioncode = "commu_incentive_towelbunbun_1507" });
            ret.Add(new ACTION_ITEM { name = "挙手", actioncode = "commu_kyoshu" });
            ret.Add(new ACTION_ITEM { name = "ダンスウィズミー", actioncode = "commu_letsdance" });
            ret.Add(new ACTION_ITEM { name = "マジカルステッキ", actioncode = "commu_magicalstick_halloween_1510" });
            ret.Add(new ACTION_ITEM { name = "カウントダウン", actioncode = "commu_newyear_countdown_1312" });
            ret.Add(new ACTION_ITEM { name = "ハッ", actioncode = "commu_nidomi" });
            ret.Add(new ACTION_ITEM { name = "うなづく", actioncode = "commu_nod" });
            ret.Add(new ACTION_ITEM { name = "プリーズ", actioncode = "commu_please" });
            ret.Add(new ACTION_ITEM { name = "サイロームーン", actioncode = "commu_sailormoon_1504" });
            ret.Add(new ACTION_ITEM { name = "フラスコ爆発", actioncode = "commu_secretlabo_1504" });
            ret.Add(new ACTION_ITEM { name = "ちがう", actioncode = "commu_shake" });
            ret.Add(new ACTION_ITEM { name = "棒術", actioncode = "commu_stickaction_1503" });
            ret.Add(new ACTION_ITEM { name = "ウルトラマン スペシウム光線", actioncode = "commu_ultraman_spacium" });
            ret.Add(new ACTION_ITEM { name = "水鉄砲バンバンバン", actioncode = "commu_watergun_1605" });
            ret.Add(new ACTION_ITEM { name = "ハートを撃ち抜く", actioncode = "commu_western_gunman_1311" });
            ret.Add(new ACTION_ITEM { name = "指輪渡し", actioncode = "commu_yubiwa_1306" });
            ret.Add(new ACTION_ITEM { name = "ゆらゆらシャキン", actioncode = "commu_yurayurashakin_1411" });
            ret.Add(new ACTION_ITEM { name = "５周年記念ダンス", actioncode = "dance_5th" });
            ret.Add(new ACTION_ITEM { name = "バク宙２回転", actioncode = "dance_5th_bakuchu" });
            ret.Add(new ACTION_ITEM { name = "サンバ", actioncode = "dance_a_samba_1202" });
            ret.Add(new ACTION_ITEM { name = "ジャンプアクション", actioncode = "dance_action_handsupjump_0804" });
            ret.Add(new ACTION_ITEM { name = "言い訳Maybe（サビロングver）", actioncode = "dance_akb48" });
            ret.Add(new ACTION_ITEM { name = "言い訳Maybe(ショートver)", actioncode = "dance_akb48_maybe" });
            ret.Add(new ACTION_ITEM { name = "君について(サビキメver)", actioncode = "dance_akb48_mint" });
            ret.Add(new ACTION_ITEM { name = "君について（サビキメver）", actioncode = "dance_akb48_mint_secret" });
            ret.Add(new ACTION_ITEM { name = "RIVER（サビキメver）", actioncode = "dance_akb48_river" });
            ret.Add(new ACTION_ITEM { name = "Alice Nine 逆ダイ", actioncode = "dance_alicenine_gyakudai_1210" });
            ret.Add(new ACTION_ITEM { name = "Alice Nine モッシュ", actioncode = "dance_alicenine_mosh_1210" });
            ret.Add(new ACTION_ITEM { name = "Alice Nine 咲き", actioncode = "dance_alicenine_saki_1210" });
            ret.Add(new ACTION_ITEM { name = "Alice Nine 横ヘドバン", actioncode = "dance_alicenine_yokoheadbang_1210" });
            ret.Add(new ACTION_ITEM { name = "あやまんJAPAN　右マッチョ、左マッチョ", actioncode = "dance_ayaman_maccho" });
            ret.Add(new ACTION_ITEM { name = "あやまんJAPAN にんにんにん", actioncode = "dance_ayaman_ninnin" });
            ret.Add(new ACTION_ITEM { name = "あやまんJAPAN ぽいぽいぽぴー", actioncode = "dance_ayaman_poipoi" });
            ret.Add(new ACTION_ITEM { name = "あやまんJAPAN しゅっしゅっぽっぽ", actioncode = "dance_ayaman_shushupopo" });
            ret.Add(new ACTION_ITEM { name = "バレリーナ", actioncode = "dance_ballerina" });
            ret.Add(new ACTION_ITEM { name = "ヘドバン", actioncode = "dance_band_hedoban" });
            ret.Add(new ACTION_ITEM { name = "歌う", actioncode = "dance_band_sing_s" });
            ret.Add(new ACTION_ITEM { name = "歌う２", actioncode = "dance_band_sing_w" });
            ret.Add(new ACTION_ITEM { name = "盆踊り", actioncode = "dance_bonodori" });
            ret.Add(new ACTION_ITEM { name = "盆踊り２０１２", actioncode = "dance_bonodori_1208" });
            ret.Add(new ACTION_ITEM { name = "盆踊り2014", actioncode = "dance_bonodori_1408" });
            ret.Add(new ACTION_ITEM { name = "盆踊り2011", actioncode = "dance_bonodori2" });
            ret.Add(new ACTION_ITEM { name = "ディスコ", actioncode = "dance_bubble" });
            ret.Add(new ACTION_ITEM { name = "ラインダンス", actioncode = "dance_cancan" });
            ret.Add(new ACTION_ITEM { name = "ベガスのショータイムなダンス", actioncode = "dance_casino_line" });
            ret.Add(new ACTION_ITEM { name = "クリスマスキャンキャン", actioncode = "dance_casino_moulin_cancan" });
            ret.Add(new ACTION_ITEM { name = "にゃんにゃんダンス", actioncode = "dance_cat_1411" });
            ret.Add(new ACTION_ITEM { name = "チャイニーズゾンビアクション", actioncode = "dance_china_yuyu_1203" });
            ret.Add(new ACTION_ITEM { name = "Choo Choo TRAIN", actioncode = "dance_choochootrain" });
            ret.Add(new ACTION_ITEM { name = "拍手", actioncode = "dance_clap_secret" });
            ret.Add(new ACTION_ITEM { name = "クリオネ", actioncode = "dance_clione_1212" });
            ret.Add(new ACTION_ITEM { name = "ええじゃないか", actioncode = "dance_eejanaika" });
            ret.Add(new ACTION_ITEM { name = "エジプトの踊り", actioncode = "dance_egypt" });
            ret.Add(new ACTION_ITEM { name = "チューチュートレイン", actioncode = "dance_exile_choochootrain_1206" });
            ret.Add(new ACTION_ITEM { name = "EXILE Rising Sun", actioncode = "dance_exile_risingsun_1206" });
            ret.Add(new ACTION_ITEM { name = "EXILE VICTORY(サビver)", actioncode = "dance_exile_victory_1206" });
            ret.Add(new ACTION_ITEM { name = "EXILEビクトリーハンズ", actioncode = "dance_exile_victory_hands_1206" });
            ret.Add(new ACTION_ITEM { name = "Exileビクトリーおおーえおー", actioncode = "dance_exile_victory_ooeo_1206" });
            ret.Add(new ACTION_ITEM { name = "ポロロの踊り", actioncode = "dance_fishing_pororo" });
            ret.Add(new ACTION_ITEM { name = "うおうおの舞", actioncode = "dance_fishing_uouo" });
            ret.Add(new ACTION_ITEM { name = "サイバーアイドル", actioncode = "dance_fishing_virtualjellyfishdol_1302" });
            ret.Add(new ACTION_ITEM { name = "サイバーアイドル", actioncode = "dance_fishing_virtualjellyfishidol_1302" });
            ret.Add(new ACTION_ITEM { name = "ガールズヒップホップダンス", actioncode = "dance_girlshiphop_1207" });
            ret.Add(new ACTION_ITEM { name = "ヘッドスピン", actioncode = "dance_headspin" });
            ret.Add(new ACTION_ITEM { name = "ハート", actioncode = "dance_heart_secret" });
            ret.Add(new ACTION_ITEM { name = "フラフープ", actioncode = "dance_hulahoop_1310" });
            ret.Add(new ACTION_ITEM { name = "ブロードウェイのJAZZダンス", actioncode = "dance_jazz1" });
            ret.Add(new ACTION_ITEM { name = "ジャンプ", actioncode = "dance_jump_secret" });
            ret.Add(new ACTION_ITEM { name = "カエルダンス", actioncode = "dance_kaeru" });
            ret.Add(new ACTION_ITEM { name = "カニダンス", actioncode = "dance_kani" });
            ret.Add(new ACTION_ITEM { name = "ピグレナ", actioncode = "dance_macarena" });
            ret.Add(new ACTION_ITEM { name = "ミクダンス１", actioncode = "dance_miku_oddsandends_1209" });
            ret.Add(new ACTION_ITEM { name = "初音ミクダンス（ミクver）４", actioncode = "dance_miku_senbonzakura_1302" });
            ret.Add(new ACTION_ITEM { name = "ミクダンス３", actioncode = "dance_miku_shoshitsu_1209" });
            ret.Add(new ACTION_ITEM { name = "ミクダンス４", actioncode = "dance_miku_worldismine_1209" });
            ret.Add(new ACTION_ITEM { name = "モーニング娘　ハンター", actioncode = "dance_morning_lhunter_1203" });
            ret.Add(new ACTION_ITEM { name = "モーニング娘。のLOVEマシーンダンス", actioncode = "dance_morning_lovemachine_1203" });
            ret.Add(new ACTION_ITEM { name = "朝までオールナイトダンシング", actioncode = "dance_nana_nomal" });
            ret.Add(new ACTION_ITEM { name = "ヲタ芸(PPPH)", actioncode = "dance_otagei_ppph_1211" });
            ret.Add(new ACTION_ITEM { name = "ヲタゲー(ロマンス)", actioncode = "dance_otagei_romance_1507" });
            ret.Add(new ACTION_ITEM { name = "パラパラ", actioncode = "dance_parapara" });
            ret.Add(new ACTION_ITEM { name = "ペンライト", actioncode = "dance_penlight" });
            ret.Add(new ACTION_ITEM { name = "ペンライト", actioncode = "dance_penlight_secret" });
            ret.Add(new ACTION_ITEM { name = "ピグCM", actioncode = "dance_pigg_cm" });
            ret.Add(new ACTION_ITEM { name = "サイドステップ", actioncode = "dance_rhythmical" });
            ret.Add(new ACTION_ITEM { name = "ロボットダンス", actioncode = "dance_robot_1502" });
            ret.Add(new ACTION_ITEM { name = "ランニングマン", actioncode = "dance_runningman_1508" });
            ret.Add(new ACTION_ITEM { name = "サンバダンス", actioncode = "dance_samba" });
            ret.Add(new ACTION_ITEM { name = "セクシーポーズ", actioncode = "dance_sexy" });
            ret.Add(new ACTION_ITEM { name = "歌う", actioncode = "dance_song" });
            ret.Add(new ACTION_ITEM { name = "サマーダンス", actioncode = "dance_summer2013" });
            ret.Add(new ACTION_ITEM { name = "縦ノリ", actioncode = "dance_tatenori" });
            ret.Add(new ACTION_ITEM { name = "ノリノリ", actioncode = "dance_tezensu_1411" });
            ret.Add(new ACTION_ITEM { name = "ゾンビちゃんダンス", actioncode = "dance_thriller" });
            ret.Add(new ACTION_ITEM { name = "ツイスト", actioncode = "dance_twist" });
            ret.Add(new ACTION_ITEM { name = "海賊の踊り", actioncode = "dance_viking" });
            ret.Add(new ACTION_ITEM { name = "噴火の舞", actioncode = "dance_volcano" });
            ret.Add(new ACTION_ITEM { name = "あげあげジャンプ", actioncode = "dance_winds_01_1106" });
            ret.Add(new ACTION_ITEM { name = "あげあげ拍手", actioncode = "dance_winds_02_1106" });
            ret.Add(new ACTION_ITEM { name = "あげあげ手拍子", actioncode = "dance_winds_03_1106" });
            ret.Add(new ACTION_ITEM { name = "ペンライトwind", actioncode = "dance_windspenlight" });
            ret.Add(new ACTION_ITEM { name = "ペンライト", actioncode = "dance_windspenlight_secret" });
            ret.Add(new ACTION_ITEM { name = "タオルブンブン", actioncode = "dance_windstowel" });
            ret.Add(new ACTION_ITEM { name = "w-indsのタオル回し", actioncode = "dance_windstowel_secret" });
            ret.Add(new ACTION_ITEM { name = "ダーツ", actioncode = "darts" });
            ret.Add(new ACTION_ITEM { name = "はあ", actioncode = "deep_tameiki" });
            ret.Add(new ACTION_ITEM { name = "殴る", actioncode = "egashira_monomousu_1407" });
            ret.Add(new ACTION_ITEM { name = "ものもうす２", actioncode = "egashira_monomousu_2_1407" });
            ret.Add(new ACTION_ITEM { name = "逆立ち", actioncode = "egashira_syachihoko_1407" });
            ret.Add(new ACTION_ITEM { name = "にゃんきゃっちアクション バトルアタック", actioncode = "event_3d_battle_attack_approach_min" });
            ret.Add(new ACTION_ITEM { name = "にゃんきゃっちアクション コールダブルハンド", actioncode = "event_3d_battle_attack_call_doublehands" });
            ret.Add(new ACTION_ITEM { name = "にゃんきゃっちアクション コールクラップ", actioncode = "event_3d_battle_attack_call_doublehands_clap" });
            ret.Add(new ACTION_ITEM { name = "にゃんきゃっちアクション コールダブルハンドハード", actioncode = "event_3d_battle_attack_call_doublehands_hard" });
            ret.Add(new ACTION_ITEM { name = "にゃんきゃっちアクション コールダブルハンドソーハード", actioncode = "event_3d_battle_attack_call_doublehands_sohard" });
            ret.Add(new ACTION_ITEM { name = "にゃんきゃっちアクション コールワンハンド", actioncode = "event_3d_battle_attack_call_onehand" });
            ret.Add(new ACTION_ITEM { name = "にゃんきゃっちアクション コールワンハンドスパリング", actioncode = "event_3d_battle_attack_call_onehand_sparingly" });
            ret.Add(new ACTION_ITEM { name = "にゃんきゃっちアクション デフォルトループダメージ０", actioncode = "event_3d_battle_default_loop_damage0" });
            ret.Add(new ACTION_ITEM { name = "にゃんきゃっちアクション デフォルトループダメージ１", actioncode = "event_3d_battle_default_loop_damage1" });
            ret.Add(new ACTION_ITEM { name = "にゃんきゃっちアクション デフォルトスタート", actioncode = "event_3d_battle_default_start" });
            ret.Add(new ACTION_ITEM { name = "にゃんきゃっちアクション ゲット", actioncode = "event_3d_battle_get" });
            ret.Add(new ACTION_ITEM { name = "にゃんきゃっちアクション 抱っこ", actioncode = "event_3d_battle_get_dakko" });
            ret.Add(new ACTION_ITEM { name = "にゃんきゃっちアクション 失敗", actioncode = "event_3d_battle_get_failed" });
            ret.Add(new ACTION_ITEM { name = "にゃんきゃっちアクション キス", actioncode = "event_3d_battle_get_kiss" });
            ret.Add(new ACTION_ITEM { name = "にゃんきゃっちアクション スリスリ", actioncode = "event_3d_battle_get_surisuri" });
            ret.Add(new ACTION_ITEM { name = "にゃんきゃっちアクション すわり_dance", actioncode = "event_3d_battle_get_suwari_dance" });
            ret.Add(new ACTION_ITEM { name = "にゃんきゃっちアクション 高い高い", actioncode = "event_3d_battle_get_takaitakai" });
            ret.Add(new ACTION_ITEM { name = "にゃんきゃっちアクション 高い高いリターン", actioncode = "event_3d_battle_get_takaitakai_return" });
            ret.Add(new ACTION_ITEM { name = "にゃんきゃっちアクション わしゃわしゃ", actioncode = "event_3d_battle_get_washawasha" });
            ret.Add(new ACTION_ITEM { name = "にゃんきゃっちアクション アイテムボール", actioncode = "event_3d_battle_item_action_ball" });
            ret.Add(new ACTION_ITEM { name = "にゃんきゃっちアクション アイテムハンド", actioncode = "event_3d_battle_item_action_hand" });
            ret.Add(new ACTION_ITEM { name = "にゃんきゃっちアクション アイテムテスト", actioncode = "event_3d_battle_item_test" });
            ret.Add(new ACTION_ITEM { name = "にゃんきゃっちアクション ジャンプ失敗", actioncode = "event_3d_field_jump_default" });
            ret.Add(new ACTION_ITEM { name = "にゃんきゃっちアクション クラウチングスタート失敗", actioncode = "event_3d_field_run_crouching" });
            ret.Add(new ACTION_ITEM { name = "にゃんきゃっちアクション ラン失敗", actioncode = "event_3d_field_run_default" });
            ret.Add(new ACTION_ITEM { name = "ｷｬｲｰﾝwwww", actioncode = "event_5th_reaction_go" });
            ret.Add(new ACTION_ITEM { name = "構える", actioncode = "event_5th_reaction_standby" });
            ret.Add(new ACTION_ITEM { name = "６周年アメチェンジ", actioncode = "event_6th_amebar_exchange" });
            ret.Add(new ACTION_ITEM { name = "６周年アメチェンジ０", actioncode = "event_6th_amebar_exchange0" });
            ret.Add(new ACTION_ITEM { name = "アメバー投げる2", actioncode = "event_6th_amebar_exchange1" });
            ret.Add(new ACTION_ITEM { name = "６周年アメチェンジ２", actioncode = "event_6th_amebar_exchange2" });
            ret.Add(new ACTION_ITEM { name = "アメバー", actioncode = "event_6th_center_getbar" });
            ret.Add(new ACTION_ITEM { name = "アメバーゲット", actioncode = "event_6th_center_getbar2" });
            ret.Add(new ACTION_ITEM { name = "ピグダイバー", actioncode = "event_6th_center_getbar3" });
            ret.Add(new ACTION_ITEM { name = "ハート", actioncode = "event_6th_center_getheart" });
            ret.Add(new ACTION_ITEM { name = "ハートゲット", actioncode = "event_6th_center_getheart2" });
            ret.Add(new ACTION_ITEM { name = "ピグダイバーハートゲット", actioncode = "event_6th_center_getheart3" });
            ret.Add(new ACTION_ITEM { name = "消える", actioncode = "event_6th_center_into_the_ufo" });
            ret.Add(new ACTION_ITEM { name = "消える2", actioncode = "event_6th_center_into_the_ufo_wait" });
            ret.Add(new ACTION_ITEM { name = "消える", actioncode = "event_6th_center_into_the_ufo2" });
            ret.Add(new ACTION_ITEM { name = "ピグダイバー消える", actioncode = "event_6th_center_into_the_ufo3" });
            ret.Add(new ACTION_ITEM { name = "回転", actioncode = "event_6th_center_korobu" });
            ret.Add(new ACTION_ITEM { name = "転ぶ", actioncode = "event_6th_center_korobu2" });
            ret.Add(new ACTION_ITEM { name = "ピグダイバー 転ぶ", actioncode = "event_6th_center_korobu3" });
            ret.Add(new ACTION_ITEM { name = "飛ぶ", actioncode = "event_6th_center_run" });
            ret.Add(new ACTION_ITEM { name = "飛び続ける", actioncode = "event_6th_center_run_move" });
            ret.Add(new ACTION_ITEM { name = "ダウン", actioncode = "event_6th_center_run_move_down" });
            ret.Add(new ACTION_ITEM { name = "ダウン", actioncode = "event_6th_center_run_move_down2" });
            ret.Add(new ACTION_ITEM { name = "ピグダイバーダウン", actioncode = "event_6th_center_run_move_down3" });
            ret.Add(new ACTION_ITEM { name = "広げる", actioncode = "event_6th_center_run_move_horizon" });
            ret.Add(new ACTION_ITEM { name = "ピグダイバー飛ぶ2", actioncode = "event_6th_center_run_move_horizon2" });
            ret.Add(new ACTION_ITEM { name = "アップ", actioncode = "event_6th_center_run_move_up" });
            ret.Add(new ACTION_ITEM { name = "走る", actioncode = "event_6th_center_run2" });
            ret.Add(new ACTION_ITEM { name = "ピグダイバー 飛ぶ", actioncode = "event_6th_center_run3" });
            ret.Add(new ACTION_ITEM { name = "センター", actioncode = "event_6th_center_tired1_1" });
            ret.Add(new ACTION_ITEM { name = "センター2", actioncode = "event_6th_center_tired1_2" });
            ret.Add(new ACTION_ITEM { name = "クルクル回る", actioncode = "event_6th_center_tired1_3" });
            ret.Add(new ACTION_ITEM { name = "回転する", actioncode = "event_6th_center_tired1_3_nobar" });
            ret.Add(new ACTION_ITEM { name = "落ちる", actioncode = "event_6th_center_waiting" });
            ret.Add(new ACTION_ITEM { name = "６周年ゲームオーバー", actioncode = "event_6th_exit_gameover" });
            ret.Add(new ACTION_ITEM { name = "ナビゾウ", actioncode = "event_6th_into_the_navizou" });
            ret.Add(new ACTION_ITEM { name = "アメバー", actioncode = "event_6th_left_getbar" });
            ret.Add(new ACTION_ITEM { name = "ハート", actioncode = "event_6th_left_getheart" });
            ret.Add(new ACTION_ITEM { name = "なんか乗って消える", actioncode = "event_6th_left_into_the_ufo_wait" });
            ret.Add(new ACTION_ITEM { name = "飛びながら回る", actioncode = "event_6th_left_korobu" });
            ret.Add(new ACTION_ITEM { name = "飛ぶ", actioncode = "event_6th_left_run" });
            ret.Add(new ACTION_ITEM { name = "６周年ゲーム２疲れる", actioncode = "event_6th_left_tired1_1" });
            ret.Add(new ACTION_ITEM { name = "６周年ゲーム２もっと疲れる", actioncode = "event_6th_left_tired1_2" });
            ret.Add(new ACTION_ITEM { name = "６周年ゲーム２激しく疲れる", actioncode = "event_6th_left_tired1_3" });
            ret.Add(new ACTION_ITEM { name = "さかさま", actioncode = "event_6th_left_tired1_3_nobar" });
            ret.Add(new ACTION_ITEM { name = "６周年ゲーム２疲れる２", actioncode = "event_6th_left_tired2_1" });
            ret.Add(new ACTION_ITEM { name = "６周年ゲーム２もっと疲れる２", actioncode = "event_6th_left_tired2_2" });
            ret.Add(new ACTION_ITEM { name = "６周年ゲーム２激しく疲れる２", actioncode = "event_6th_left_tired2_3" });
            ret.Add(new ACTION_ITEM { name = "６周年ゲーム２疲れる３", actioncode = "event_6th_left_tired3_1" });
            ret.Add(new ACTION_ITEM { name = "６周年ゲーム２もっと疲れる３", actioncode = "event_6th_left_tired3_2" });
            ret.Add(new ACTION_ITEM { name = "６周年ゲーム２激しく疲れる３", actioncode = "event_6th_left_tired3_3" });
            ret.Add(new ACTION_ITEM { name = "飛行機みたいな物体に乗る", actioncode = "event_6th_left_waiting" });
            ret.Add(new ACTION_ITEM { name = "６周年レベルアップゲーム３", actioncode = "event_6th_levelup_center" });
            ret.Add(new ACTION_ITEM { name = "６周年レベルアップゲーム２", actioncode = "event_6th_levelup_left" });
            ret.Add(new ACTION_ITEM { name = "６周年レベルアップゲーム１", actioncode = "event_6th_levelup_right" });
            ret.Add(new ACTION_ITEM { name = "６周年ナビ像ボールプールうごく", actioncode = "event_6th_navizou_burying_move" });
            ret.Add(new ACTION_ITEM { name = "上がる", actioncode = "event_6th_navizou_burying_move_out" });
            ret.Add(new ACTION_ITEM { name = "ナビゾウ3", actioncode = "event_6th_navizou_burying_move2" });
            ret.Add(new ACTION_ITEM { name = "ナビゾウ4", actioncode = "event_6th_navizou_burying_move3" });
            ret.Add(new ACTION_ITEM { name = "６周年ナビ像回る", actioncode = "event_6th_navizou_rolling" });
            ret.Add(new ACTION_ITEM { name = "パラシュート 6周年", actioncode = "event_6th_parachute_navizou" });
            ret.Add(new ACTION_ITEM { name = "パラシュート ピンク", actioncode = "event_6th_parachute1" });
            ret.Add(new ACTION_ITEM { name = "パラシュート 緑", actioncode = "event_6th_parachute2" });
            ret.Add(new ACTION_ITEM { name = "パラシュート オレンジ", actioncode = "event_6th_parachute3" });
            ret.Add(new ACTION_ITEM { name = "ゲットアメバー", actioncode = "event_6th_right_getbar" });
            ret.Add(new ACTION_ITEM { name = "ゲットハート", actioncode = "event_6th_right_getheart" });
            ret.Add(new ACTION_ITEM { name = "６周年ゲーム１UFOに入る", actioncode = "event_6th_right_into_the_ufo" });
            ret.Add(new ACTION_ITEM { name = "転ぶ", actioncode = "event_6th_right_korobu" });
            ret.Add(new ACTION_ITEM { name = "走る", actioncode = "event_6th_right_run" });
            ret.Add(new ACTION_ITEM { name = "疲れる", actioncode = "event_6th_right_tired1_1" });
            ret.Add(new ACTION_ITEM { name = "アメバー落とす", actioncode = "event_6th_right_tired1_3" });
            ret.Add(new ACTION_ITEM { name = "転ぶ", actioncode = "event_6th_right_tired1_3_nobar" });
            ret.Add(new ACTION_ITEM { name = "変なのにのって走る", actioncode = "event_6th_right_waiting" });
            ret.Add(new ACTION_ITEM { name = "7周年パーク 雲に沈む", actioncode = "event_7th_sink_loop" });
            ret.Add(new ACTION_ITEM { name = "7周年パーク 雲に沈むアクション", actioncode = "event_7th_sink_start" });
            ret.Add(new ACTION_ITEM { name = "回る", actioncode = "event_aare" });
            ret.Add(new ACTION_ITEM { name = "暴れる", actioncode = "event_downBataBata" });
            ret.Add(new ACTION_ITEM { name = "ドラゴンボール 悟空のジャンプ", actioncode = "event_dragonball_jumpGoku" });
            ret.Add(new ACTION_ITEM { name = "ドラゴンボール オッス", actioncode = "event_dragonball_ossuGoku" });
            ret.Add(new ACTION_ITEM { name = "ドラゴンボール 登場アクション", actioncode = "event_dragonball_showGoku" });
            ret.Add(new ACTION_ITEM { name = "水を飲む", actioncode = "event_drink_lv1" });
            ret.Add(new ACTION_ITEM { name = "５周年ドリンクレベル２", actioncode = "event_drink_lv2" });
            ret.Add(new ACTION_ITEM { name = "５周年ドリンクレベル３", actioncode = "event_drink_lv3" });
            ret.Add(new ACTION_ITEM { name = "５周年ドリンクレベル４", actioncode = "event_drink_lv4" });
            ret.Add(new ACTION_ITEM { name = "水を吹く", actioncode = "event_drink_over" });
            ret.Add(new ACTION_ITEM { name = "敬礼", actioncode = "event_drink_stand" });
            ret.Add(new ACTION_ITEM { name = "疲れる", actioncode = "event_drink_tired" });
            ret.Add(new ACTION_ITEM { name = "江頭シャウト", actioncode = "event_egashira_shout" });
            ret.Add(new ACTION_ITEM { name = "ストーム３_action", actioncode = "event_eventStorm3_action" });
            ret.Add(new ACTION_ITEM { name = "1回転", actioncode = "event_eventStormRolling" });
            ret.Add(new ACTION_ITEM { name = "５周年ガンショット", actioncode = "event_gun_shot" });
            ret.Add(new ACTION_ITEM { name = "ハロウィーンラン", actioncode = "event_halloween2015_run" });
            ret.Add(new ACTION_ITEM { name = "ハロウィーンウェイブチャージ", actioncode = "event_halloween2015_wave_charge" });
            ret.Add(new ACTION_ITEM { name = "ハロウィーンウェイブショット", actioncode = "event_halloween2015_wave_shot" });
            ret.Add(new ACTION_ITEM { name = "走る", actioncode = "event_haunted_anatomical_run" });
            ret.Add(new ACTION_ITEM { name = "人体切断", actioncode = "event_haunted_npc_break" });
            ret.Add(new ACTION_ITEM { name = "病院スタンドバイ", actioncode = "event_haunted_npc_standby" });
            ret.Add(new ACTION_ITEM { name = "病院NPC歩く", actioncode = "event_haunted_npc_walk" });
            ret.Add(new ACTION_ITEM { name = "プリーズ", actioncode = "event_haunted_standby" });
            ret.Add(new ACTION_ITEM { name = "歩く", actioncode = "event_haunted_walk" });
            ret.Add(new ACTION_ITEM { name = "病院アタック", actioncode = "event_haunted2015_attack" });
            ret.Add(new ACTION_ITEM { name = "病院敵１ランストップ", actioncode = "event_haunted2015_enemy01_run_stop" });
            ret.Add(new ACTION_ITEM { name = "病院敵１ラントランス", actioncode = "event_haunted2015_enemy01_run_trace" });
            ret.Add(new ACTION_ITEM { name = "病院敵１トラップ", actioncode = "event_haunted2015_enemy01_run_trap" });
            ret.Add(new ACTION_ITEM { name = "病院ガクブル２", actioncode = "event_haunted2015_gakuburu_02" });
            ret.Add(new ACTION_ITEM { name = "病院ガクブル４", actioncode = "event_haunted2015_gakuburu_04" });
            ret.Add(new ACTION_ITEM { name = "病院ガクブルダウン", actioncode = "event_haunted2015_gakuburu_down_01" });
            ret.Add(new ACTION_ITEM { name = "病院箱の中エンド", actioncode = "event_haunted2015_inbox_end" });
            ret.Add(new ACTION_ITEM { name = "病院箱の中ループ", actioncode = "event_haunted2015_inbox_loop" });
            ret.Add(new ACTION_ITEM { name = "病院箱の中スタート", actioncode = "event_haunted2015_inbox_start" });
            ret.Add(new ACTION_ITEM { name = "病院ユーザートランスウォーク", actioncode = "event_haunted2015_user_trace_walk" });
            ret.Add(new ACTION_ITEM { name = "病院ワクチンチェンジ０", actioncode = "event_haunted2015_vaccine_exchange0" });
            ret.Add(new ACTION_ITEM { name = "病院ワクチンチェンジ１", actioncode = "event_haunted2015_vaccine_exchange1" });
            ret.Add(new ACTION_ITEM { name = "病院ワクチンチェンジ２", actioncode = "event_haunted2015_vaccine_exchange2" });
            ret.Add(new ACTION_ITEM { name = "病院起きる", actioncode = "event_haunted2015_wakeup" });
            ret.Add(new ACTION_ITEM { name = "ハロウィーン２０１６アフターお化け", actioncode = "event_hw2016_hole_fall_after_obake" });
            ret.Add(new ACTION_ITEM { name = "ハロウィーン２０１６お化け", actioncode = "event_hw2016_hole_fall_obake" });
            ret.Add(new ACTION_ITEM { name = "ハロウィーン２０１６ビフォアーお化け", actioncode = "event_hw2016_mirror_before" });
            ret.Add(new ACTION_ITEM { name = "ハロウィーンお化け飛び込む", actioncode = "event_hw2016_mirror_fall" });
            ret.Add(new ACTION_ITEM { name = "踊る", actioncode = "event_hwe_wait" });
            ret.Add(new ACTION_ITEM { name = "シネマハイド", actioncode = "event_mh4_cinema_hide" });
            ret.Add(new ACTION_ITEM { name = "軽くジャンプ", actioncode = "event_mh4_cinema_pull" });
            ret.Add(new ACTION_ITEM { name = "下から上がる", actioncode = "event_mh4_cinema_show" });
            ret.Add(new ACTION_ITEM { name = "卵を持つ", actioncode = "event_mh4_gather" });
            ret.Add(new ACTION_ITEM { name = "肉を回す", actioncode = "event_mh4_meat" });
            ret.Add(new ACTION_ITEM { name = "肉を持つ", actioncode = "event_mh4_meat_up" });
            ret.Add(new ACTION_ITEM { name = "クエストクリア", actioncode = "event_mh4_quest_clear" });
            ret.Add(new ACTION_ITEM { name = "あわわわ", actioncode = "event_mh4_ride_bress" });
            ret.Add(new ACTION_ITEM { name = "歩く", actioncode = "event_mh4_ride_jump" });
            ret.Add(new ACTION_ITEM { name = "卵を持って歩く", actioncode = "event_mh4_run" });
            ret.Add(new ACTION_ITEM { name = "卵を持つ2", actioncode = "event_mh4_run_revive" });
            ret.Add(new ACTION_ITEM { name = "座る", actioncode = "event_mh4_sit" });
            ret.Add(new ACTION_ITEM { name = "動く", actioncode = "event_mh4_suwari_ride" });
            ret.Add(new ACTION_ITEM { name = "離れる", actioncode = "event_mh4_suwari_ride_before_bress" });
            ret.Add(new ACTION_ITEM { name = "離れる2", actioncode = "event_mh4_suwari_ride_first" });
            ret.Add(new ACTION_ITEM { name = "煙を頭にかける2016", actioncode = "event_newyear2016_kemuri" });
            ret.Add(new ACTION_ITEM { name = "手を洗う2016", actioncode = "event_newyear2016_temizu" });
            ret.Add(new ACTION_ITEM { name = "頭に乗られる2016", actioncode = "event_newyear2016_wearSaru" });
            ret.Add(new ACTION_ITEM { name = "鈴を鳴らす2016", actioncode = "event_newyear2016_worship_suzu" });
            ret.Add(new ACTION_ITEM { name = "にゃんくるず", actioncode = "event_nyanculus" });
            ret.Add(new ACTION_ITEM { name = "モンスターズオープンドアー", actioncode = "event_open_monstersIncDoor" });
            ret.Add(new ACTION_ITEM { name = "モンスターズオープンイニットドア", actioncode = "event_open_monstersIncInitDoor" });
            ret.Add(new ACTION_ITEM { name = "敵ラン１", actioncode = "event_opopo_enemy_run1" });
            ret.Add(new ACTION_ITEM { name = "倒れる", actioncode = "event_tumble" });
            ret.Add(new ACTION_ITEM { name = "クリスマス２０１６ルーフ", actioncode = "event_xmas2016_fall_roof" });
            ret.Add(new ACTION_ITEM { name = "クリスマス２０１６ルーフストライト", actioncode = "event_xmas2016_fall_roof_straight" });
            ret.Add(new ACTION_ITEM { name = "クリスマス２０１６ジャンプ", actioncode = "event_xmas2016_jump" });
            ret.Add(new ACTION_ITEM { name = "クリスマス２０１６ランチオーナメント", actioncode = "event_xmas2016_launch_ornament" });
            ret.Add(new ACTION_ITEM { name = "クリスマス２０１４ゲームスパ", actioncode = "EventXmas2014_game_spa_4001" });
            ret.Add(new ACTION_ITEM { name = "あくび", actioncode = "feel_akubi" });
            ret.Add(new ACTION_ITEM { name = "ぶんぶん", actioncode = "feel_bunbun_1410" });
            ret.Add(new ACTION_ITEM { name = "カメラ", actioncode = "feel_camera" });
            ret.Add(new ACTION_ITEM { name = "カメラ小僧", actioncode = "feel_camerakozou_1211" });
            ret.Add(new ACTION_ITEM { name = "幽玄★占い師のおふだアクション", actioncode = "feel_casino_augur_1407" });
            ret.Add(new ACTION_ITEM { name = "乱舞！バラ侍アクション", actioncode = "feel_casino_barazamurai_1405" });
            ret.Add(new ACTION_ITEM { name = "シャンパン", actioncode = "feel_casino_chanpagne_1212" });
            ret.Add(new ACTION_ITEM { name = "ギャンプラーのガッツポーズ", actioncode = "feel_casino_gambler_happy" });
            ret.Add(new ACTION_ITEM { name = "サーカスジャグリングアクション", actioncode = "feel_casino_nighthalloween_1410" });
            ret.Add(new ACTION_ITEM { name = "ベルサイユのばらをくわえる風アクション", actioncode = "feel_casino_oscar_1412" });
            ret.Add(new ACTION_ITEM { name = "かわいいでしょ", actioncode = "feel_cawaii" });
            ret.Add(new ACTION_ITEM { name = "ちぇ", actioncode = "feel_che" });
            ret.Add(new ACTION_ITEM { name = "CHU★", actioncode = "feel_chu_1603" });
            ret.Add(new ACTION_ITEM { name = "だだをこねる", actioncode = "feel_dada" });
            ret.Add(new ACTION_ITEM { name = "深呼吸", actioncode = "feel_deepbreath" });
            ret.Add(new ACTION_ITEM { name = "土下座", actioncode = "feel_dogeza_1210" });
            ret.Add(new ACTION_ITEM { name = "わー恥ずかしい", actioncode = "feel_embarrassed" });
            ret.Add(new ACTION_ITEM { name = "スマイル", actioncode = "feel_face_smile" });
            ret.Add(new ACTION_ITEM { name = "ピチピチ", actioncode = "feel_fishing_pichipichi_1304" });
            ret.Add(new ACTION_ITEM { name = "ふなっしー高速ヘドバン", actioncode = "feel_funassy_headbang_1403" });
            ret.Add(new ACTION_ITEM { name = "ふなっしー 大ジャンプ", actioncode = "feel_funassy_jump_1403" });
            ret.Add(new ACTION_ITEM { name = "ガーン", actioncode = "feel_gaan" });
            ret.Add(new ACTION_ITEM { name = "えびぞりガクブル", actioncode = "feel_gakuburu_ame_1507" });
            ret.Add(new ACTION_ITEM { name = "満腹", actioncode = "feel_gep_1501" });
            ret.Add(new ACTION_ITEM { name = "ヒーローの真似っ子", actioncode = "feel_hero_imitation_1405" });
            ret.Add(new ACTION_ITEM { name = "ごろにゃん キッスアクション", actioncode = "feel_incentive_goronyankiss_1602" });
            ret.Add(new ACTION_ITEM { name = "うたたね", actioncode = "feel_incentive_utatane_1605" });
            ret.Add(new ACTION_ITEM { name = "祈る", actioncode = "feel_inori_1412" });
            ret.Add(new ACTION_ITEM { name = "いただきまーす", actioncode = "feel_itadakimasu_1511" });
            ret.Add(new ACTION_ITEM { name = "鳥になりたい", actioncode = "feel_iwereabird_1210" });
            ret.Add(new ACTION_ITEM { name = "ものすごく怒る", actioncode = "feel_jidanda" });
            ret.Add(new ACTION_ITEM { name = "ジャンピング土下座", actioncode = "feel_jumpingdogeza_1210" });
            ret.Add(new ACTION_ITEM { name = "鬼太郎のリモコン下駄", actioncode = "feel_kitarou_1407" });
            ret.Add(new ACTION_ITEM { name = "ガクブル", actioncode = "feel_kowai" });
            ret.Add(new ACTION_ITEM { name = "おかしくてたまらない", actioncode = "feel_laugh_banban_1404" });
            ret.Add(new ACTION_ITEM { name = "大笑い", actioncode = "feel_laugh_large" });
            ret.Add(new ACTION_ITEM { name = "モジモジ(男)", actioncode = "feel_mojimoji_boy" });
            ret.Add(new ACTION_ITEM { name = "モンキージャンプ", actioncode = "feel_monkey_jump_1601" });
            ret.Add(new ACTION_ITEM { name = "もじもじ", actioncode = "feel_mozimozi" });
            ret.Add(new ACTION_ITEM { name = "投げキッス", actioncode = "feel_nagekiss_big_1209" });
            ret.Add(new ACTION_ITEM { name = "Ｗ投げキッス", actioncode = "feel_nagekiss_super_1209" });
            ret.Add(new ACTION_ITEM { name = "悩む", actioncode = "feel_nayamu" });
            ret.Add(new ACTION_ITEM { name = "にゃんにゃん", actioncode = "feel_nyannyan_1605" });
            ret.Add(new ACTION_ITEM { name = "お化けぴょんぴょん", actioncode = "feel_obakepyonpyon_1410" });
            ret.Add(new ACTION_ITEM { name = "めちゃイケ 江頭のものまね", actioncode = "feel_ofc_mechaike_ega_mono" });
            ret.Add(new ACTION_ITEM { name = "３連物申す", actioncode = "feel_ofc_mechaike_ega_mono3" });
            ret.Add(new ACTION_ITEM { name = "ぱたんピクピク", actioncode = "feel_patanpikupiku_1507" });
            ret.Add(new ACTION_ITEM { name = "ぽっ", actioncode = "feel_po" });
            ret.Add(new ACTION_ITEM { name = "本を読む", actioncode = "feel_readbook_1611" });
            ret.Add(new ACTION_ITEM { name = "マイクコードパフォーマンス", actioncode = "feel_rollingmic_1305" });
            ret.Add(new ACTION_ITEM { name = "屋上で叫ぶ", actioncode = "feel_shibugaku_shout" });
            ret.Add(new ACTION_ITEM { name = "屋上で寝る", actioncode = "feel_shibugaku_sleep" });
            ret.Add(new ACTION_ITEM { name = "忍び足", actioncode = "feel_shinobiashi_1501" });
            ret.Add(new ACTION_ITEM { name = "シュピーーン！", actioncode = "feel_shupiiin_1503" });
            ret.Add(new ACTION_ITEM { name = "手裏剣投げ", actioncode = "feel_shuriken_1501" });
            ret.Add(new ACTION_ITEM { name = "スチャ", actioncode = "feel_sucha_1505" });
            ret.Add(new ACTION_ITEM { name = "びっくり", actioncode = "feel_surprise" });
            ret.Add(new ACTION_ITEM { name = "座りブルブル", actioncode = "feel_suwariBuruburu" });
            ret.Add(new ACTION_ITEM { name = "ズッギャーーン", actioncode = "feel_syndrome_1503" });
            ret.Add(new ACTION_ITEM { name = "ゲゲゲの鬼太郎アタック", actioncode = "feel_syunobon_attack" });
            ret.Add(new ACTION_ITEM { name = "ゲゲゲの鬼太郎 埋められるアクション", actioncode = "feel_syunobon_bokoboko" });
            ret.Add(new ACTION_ITEM { name = "穴から出る", actioncode = "feel_syunobon_bokoboko_mogaku1" });
            ret.Add(new ACTION_ITEM { name = "考える", actioncode = "feel_thinking" });
            ret.Add(new ACTION_ITEM { name = "うさぎピョンピョン", actioncode = "feel_usagi_pyonpyon_1509" });
            ret.Add(new ACTION_ITEM { name = "うとうと", actioncode = "feel_utouto" });
            ret.Add(new ACTION_ITEM { name = "手渡し", actioncode = "feel_valentine" });
            ret.Add(new ACTION_ITEM { name = "ワッ！", actioncode = "feel_wa" });
            ret.Add(new ACTION_ITEM { name = "みずやり", actioncode = "feel_water_1405" });
            ret.Add(new ACTION_ITEM { name = "やる気メラメラ", actioncode = "feel_yaruki_1505" });
            ret.Add(new ACTION_ITEM { name = "寝転がってジタバタ", actioncode = "feel_zitabata_1310" });
            ret.Add(new ACTION_ITEM { name = "継続失敗", actioncode = "fever_fail" });
            ret.Add(new ACTION_ITEM { name = "アタック(事前に釣りエリアに行く必要有)", actioncode = "fishing_attack" });
            ret.Add(new ACTION_ITEM { name = "アタックミス(事前に釣りエリアに行く必要有)", actioncode = "fishing_attack_miss" });
            ret.Add(new ACTION_ITEM { name = "バトル1(事前に釣りエリアに行く必要有)", actioncode = "fishing_battle1" });
            ret.Add(new ACTION_ITEM { name = "バトル2(事前に釣りエリアに行く必要有)", actioncode = "fishing_battle2" });
            ret.Add(new ACTION_ITEM { name = "バトル3(事前に釣りエリアに行く必要有)", actioncode = "fishing_battle3" });
            ret.Add(new ACTION_ITEM { name = "釣り(事前に釣りエリアに行く必要有)", actioncode = "fishing_chum" });
            ret.Add(new ACTION_ITEM { name = "ドリンク(事前に釣りエリアに行く必要有)", actioncode = "fishing_drink" });
            ret.Add(new ACTION_ITEM { name = "エスケープ(事前に釣りエリアに行く必要有)", actioncode = "fishing_escape" });
            ret.Add(new ACTION_ITEM { name = "失敗(事前に釣りエリアに行く必要有)", actioncode = "fishing_failure" });
            ret.Add(new ACTION_ITEM { name = "ヒット成功2(事前に釣りエリアに行く必要有)", actioncode = "fishing_hit_success" });
            ret.Add(new ACTION_ITEM { name = "ヒット成功(事前に釣りエリアに行く必要有)", actioncode = "fishing_hit_success_loop" });
            ret.Add(new ACTION_ITEM { name = "リターン(事前に釣りエリアに行く必要有)", actioncode = "fishing_return" });
            ret.Add(new ACTION_ITEM { name = "座る(事前に釣りエリアに行く必要有)", actioncode = "fishing_sit" });
            ret.Add(new ACTION_ITEM { name = "成功(事前に釣りエリアに行く必要有)", actioncode = "fishing_success" });
            ret.Add(new ACTION_ITEM { name = "投げる(事前に釣りエリアに行く必要有)", actioncode = "fishing_throw" });
            ret.Add(new ACTION_ITEM { name = "スキルを覚えた！", actioncode = "flash_skill" });
            ret.Add(new ACTION_ITEM { name = "ドリンクを飲む", actioncode = "food_drink" });
            ret.Add(new ACTION_ITEM { name = "座って飲む", actioncode = "food_drink_sit" });
            ret.Add(new ACTION_ITEM { name = "食べる", actioncode = "food_eat" });
            ret.Add(new ACTION_ITEM { name = "座って食べる", actioncode = "food_eat_sit" });
            ret.Add(new ACTION_ITEM { name = "座って食べる", actioncode = "food_eat_sit_secret" });
            ret.Add(new ACTION_ITEM { name = "食べる2", actioncode = "food_noodle" });
            ret.Add(new ACTION_ITEM { name = "座ってたべる2", actioncode = "food_noodle_sit" });
            ret.Add(new ACTION_ITEM { name = "食べる", actioncode = "food_straw" });
            ret.Add(new ACTION_ITEM { name = "座って食べる", actioncode = "food_straw_sit" });
            ret.Add(new ACTION_ITEM { name = "いらいら", actioncode = "frustrate" });
            ret.Add(new ACTION_ITEM { name = "平均台", actioncode = "furniture_balancebeam_1310" });
            ret.Add(new ACTION_ITEM { name = "ペンキ塗り", actioncode = "furniture_diy_penki_1405" });
            ret.Add(new ACTION_ITEM { name = "木を切る", actioncode = "furniture_diy_wood_1405" });
            ret.Add(new ACTION_ITEM { name = "鉄棒(大)", actioncode = "furniture_ironbar_big_1304" });
            ret.Add(new ACTION_ITEM { name = "鉄棒(小)", actioncode = "furniture_ironbar_small_1304" });
            ret.Add(new ACTION_ITEM { name = "モデル台のモデルポーズアクション", actioncode = "furniture_modelstage" });
            ret.Add(new ACTION_ITEM { name = "ダーツバー", actioncode = "furniture_neondarts_1505" });
            ret.Add(new ACTION_ITEM { name = "もちつき", actioncode = "furniture_newyear_usu_1312" });
            ret.Add(new ACTION_ITEM { name = "学校の花壇に水をやる", actioncode = "furniture_school_extr_water_1304" });
            ret.Add(new ACTION_ITEM { name = "トランポリン", actioncode = "furniture_trampoline" });
            ret.Add(new ACTION_ITEM { name = "G1アナウンス", actioncode = "g1_announce" });
            ret.Add(new ACTION_ITEM { name = "いないない～？バァッ～ｗｗｗｗ", actioncode = "g1_goto" });
            ret.Add(new ACTION_ITEM { name = "大", actioncode = "g1_makabe" });
            ret.Add(new ACTION_ITEM { name = "煙を吹く", actioncode = "g1_nagata" });
            ret.Add(new ACTION_ITEM { name = "G1中村", actioncode = "g1_nakamura" });
            ret.Add(new ACTION_ITEM { name = "手を挙げる", actioncode = "g1_nakanishi" });
            ret.Add(new ACTION_ITEM { name = "G1棚橋", actioncode = "g1_tanahashi" });
            ret.Add(new ACTION_ITEM { name = "一気飲み", actioncode = "g1_ten" });
            ret.Add(new ACTION_ITEM { name = "降ろす", actioncode = "g1_ten2" });
            ret.Add(new ACTION_ITEM { name = "上を見続ける", actioncode = "g1_ten3" });
            ret.Add(new ACTION_ITEM { name = "上を見る", actioncode = "g1_ten4" });
            ret.Add(new ACTION_ITEM { name = "ゴッド浮くときのコマンド", actioncode = "god_chant" });
            ret.Add(new ACTION_ITEM { name = "ゴッド浮遊", actioncode = "god_floating" });
            ret.Add(new ACTION_ITEM { name = "グッピグ", actioncode = "goodpigg_send" });
            ret.Add(new ACTION_ITEM { name = "ゲットする", actioncode = "haunted2014_candle_get" });
            ret.Add(new ACTION_ITEM { name = "あいさつ", actioncode = "hello" });
            ret.Add(new ACTION_ITEM { name = "フレグランス", actioncode = "item_ad_clinique_fragrance_1111" });
            ret.Add(new ACTION_ITEM { name = "コカコーラ", actioncode = "item_ad_cocacola_1112" });
            ret.Add(new ACTION_ITEM { name = "コーラを飲む", actioncode = "item_ad_cocacola_1211" });
            ret.Add(new ACTION_ITEM { name = "ギフトコーラを飲む", actioncode = "item_ad_cocacola_gift_1311" });
            ret.Add(new ACTION_ITEM { name = "エメマン缶コーヒーを飲む", actioncode = "item_ad_ememan_can_bl_1209" });
            ret.Add(new ACTION_ITEM { name = "エメマン ヨーロピアン", actioncode = "item_ad_ememan_can_european_1209" });
            ret.Add(new ACTION_ITEM { name = "エメマン/gl", actioncode = "item_ad_ememan_can_gl_1209" });
            ret.Add(new ACTION_ITEM { name = "エビアン", actioncode = "item_ad_evian_1205" });
            ret.Add(new ACTION_ITEM { name = "ジャイアントコーンクッキー ＆ チョコ", actioncode = "item_ad_glico_giantcone_bl_1304" });
            ret.Add(new ACTION_ITEM { name = "ジャイアントコーンチョコナッツ", actioncode = "item_ad_glico_giantcone_rd_1304" });
            ret.Add(new ACTION_ITEM { name = "ジャイアントコーンクッキー ＆ クリーム", actioncode = "item_ad_glico_giantcone_yw_1304" });
            ret.Add(new ACTION_ITEM { name = "ケープ", actioncode = "item_ad_kao_cape_1302" });
            ret.Add(new ACTION_ITEM { name = "アトリックスハンドクリーム", actioncode = "item_ad_kao_nivea_atrix_handcream_1109" });
            ret.Add(new ACTION_ITEM { name = "スウィートハッピー", actioncode = "item_ad_kao_nivea_sweet_happy_1110" });
            ret.Add(new ACTION_ITEM { name = "ポケムヒ・キティー", actioncode = "item_ad_muhi_pocketmuhi_1206" });
            ret.Add(new ACTION_ITEM { name = "パンテーン", actioncode = "item_ad_pantene_shampoo_1108" });
            ret.Add(new ACTION_ITEM { name = "爽健美茶おにぎりセット", actioncode = "item_ad_souken_set_onigiri_1110" });
            ret.Add(new ACTION_ITEM { name = "トマール猿人バナナ", actioncode = "item_ad_subaru_banana_1106" });
            ret.Add(new ACTION_ITEM { name = "コパトーン", actioncode = "item_ad_taisho_coppertone_1305" });
            ret.Add(new ACTION_ITEM { name = "グミゼル", actioncode = "item_ad_tetsudo_gumitzel_1403" });
            ret.Add(new ACTION_ITEM { name = "ポップスイーツ", actioncode = "item_ad_tetsudo_popsweets_1403" });
            ret.Add(new ACTION_ITEM { name = "melumo･つやつやエッセンス", actioncode = "item_ad_wakasa_lotion_1305" });
            ret.Add(new ACTION_ITEM { name = "wowowメガフォン", actioncode = "item_ad_wowow_megaphone_1110" });
            ret.Add(new ACTION_ITEM { name = "4周年・バルーンピエロ", actioncode = "item_ame_4th_balloon_pierrot_fly_1302" });
            ret.Add(new ACTION_ITEM { name = "4周年・バルーンサル", actioncode = "item_ame_4th_balloon_saru_fly_1302" });
            ret.Add(new ACTION_ITEM { name = "ハロウィンのこうもりバルーン", actioncode = "item_ame_halloween_balloon_bat_1210" });
            ret.Add(new ACTION_ITEM { name = "おばけのジェット風船", actioncode = "item_ame_halloween_jetballoon_ghost_1210" });
            ret.Add(new ACTION_ITEM { name = "７ｔｈコットンキャンディ", actioncode = "item_ame_s_7th_cottoncandy_1602" });
            ret.Add(new ACTION_ITEM { name = "タイガースバルーン", actioncode = "item_ame_tigers_balloon_1407" });
            ret.Add(new ACTION_ITEM { name = "パーティー用ピグペリーニュ(ノンアルコール)", actioncode = "item_casino_champagne" });
            ret.Add(new ACTION_ITEM { name = "コカ・コーラ デザイン缶", actioncode = "item_ccjc_olympic_cocacola_1206" });
            ret.Add(new ACTION_ITEM { name = "星に願いを", actioncode = "item_commu_pray_tanabata_1106" });
            ret.Add(new ACTION_ITEM { name = "子供ビール", actioncode = "item_countdown_beer_1112" });
            ret.Add(new ACTION_ITEM { name = "カウントダウンバルーン", actioncode = "item_countdownrandevu_s_balloon_1412" });
            ret.Add(new ACTION_ITEM { name = "お祝いクラッカー/bl", actioncode = "item_cracker_bl_1004" });
            ret.Add(new ACTION_ITEM { name = "お祝いクラッカー/gn", actioncode = "item_cracker_gn_1004" });
            ret.Add(new ACTION_ITEM { name = "お祝いクラッカー/pk", actioncode = "item_cracker_pk_1004" });
            ret.Add(new ACTION_ITEM { name = "お祝いクラッカー/rd", actioncode = "item_cracker_rd_1004" });
            ret.Add(new ACTION_ITEM { name = "団子を食べる", actioncode = "item_dango_1108" });
            ret.Add(new ACTION_ITEM { name = "魔法の杖ドリーム・シンデレラ", actioncode = "item_disney_cinderella_1303" });
            ret.Add(new ACTION_ITEM { name = "フラワーシャワー", actioncode = "item_flowershower_1306" });
            ret.Add(new ACTION_ITEM { name = "タケコプター", actioncode = "item_gacha_pc_dora_action_1109" });
            ret.Add(new ACTION_ITEM { name = "タケコプター(ドラミ)", actioncode = "item_gacha_pc_dora_tkp_dorami_1209" });
            ret.Add(new ACTION_ITEM { name = "恵方巻き・ギフト", actioncode = "item_gift_setsubun_ehomaki_1201" });
            ret.Add(new ACTION_ITEM { name = "ハロウィン・バルーン緑", actioncode = "item_halloween_balloon_hand_gn_1110" });
            ret.Add(new ACTION_ITEM { name = "ハロウィン・バルーンオレンジ", actioncode = "item_halloween_balloon_hand_or_1110" });
            ret.Add(new ACTION_ITEM { name = "ハロウィン・バルーン紫", actioncode = "item_halloween_balloon_hand_pr_1110" });
            ret.Add(new ACTION_ITEM { name = "ロケット花火", actioncode = "item_hanabi_s_rocket_1208" });
            ret.Add(new ACTION_ITEM { name = "線香花火", actioncode = "item_hanabi_s_senkou_1208" });
            ret.Add(new ACTION_ITEM { name = "1000万会員 ThankYou☆ バルーン", actioncode = "item_incentive_balloon_1000_hand_1110" });
            ret.Add(new ACTION_ITEM { name = "おかえり5周年クラッカー", actioncode = "item_incentive_comeback_cracker_1402" });
            ret.Add(new ACTION_ITEM { name = "VIP限定★リリースバルーン", actioncode = "item_incentive_vip_balloon_1508" });
            ret.Add(new ACTION_ITEM { name = "ぞうさんしゃぼんだま", actioncode = "item_incentive_vip_syabonjuu_1507" });
            ret.Add(new ACTION_ITEM { name = "クリスマスバルーン", actioncode = "item_incentive_xmas_balloon_tree_wh_1412" });
            ret.Add(new ACTION_ITEM { name = "8×4", actioncode = "item_kao_8x4_1105" });
            ret.Add(new ACTION_ITEM { name = "超きもちいい", actioncode = "item_kitajima_cho" });
            ret.Add(new ACTION_ITEM { name = "なにもいえね", actioncode = "item_kitajima_not" });
            ret.Add(new ACTION_ITEM { name = "コロッケ", actioncode = "item_kokuriko_food_croquette_1109" });
            ret.Add(new ACTION_ITEM { name = "よーよー青", actioncode = "item_matsuri_s_yoyo_bl_1208" });
            ret.Add(new ACTION_ITEM { name = "ヨーヨー/赤", actioncode = "item_matsuri_s_yoyo_rd_1208" });
            ret.Add(new ACTION_ITEM { name = "ヨーヨー/黄", actioncode = "item_matsuri_s_yoyo_yw_1208" });
            ret.Add(new ACTION_ITEM { name = "紅白ジェット風船/赤", actioncode = "item_newyear_balloon_rd_1112" });
            ret.Add(new ACTION_ITEM { name = "紅白ジェット風船/白", actioncode = "item_newyear_balloon_wh_1112" });
            ret.Add(new ACTION_ITEM { name = "新年ビール", actioncode = "item_newyearparty_s_beer_1501" });
            ret.Add(new ACTION_ITEM { name = "忍者煙玉", actioncode = "item_ninja_dron" });
            ret.Add(new ACTION_ITEM { name = "ラーメン湯切り", actioncode = "item_noodle_yukiri_1301" });
            ret.Add(new ACTION_ITEM { name = "セクシービーム", actioncode = "item_ofc_s_morning_sexybeam_1203" });
            ret.Add(new ACTION_ITEM { name = "岡田ラインメーカー", actioncode = "item_okada_rainmaker_1301" });
            ret.Add(new ACTION_ITEM { name = "うきうきくまバルーン/bl", actioncode = "item_party_balloon_bear_bl_1106" });
            ret.Add(new ACTION_ITEM { name = "うきうきくまバルーン/pk", actioncode = "item_party_balloon_bear_pk_1106" });
            ret.Add(new ACTION_ITEM { name = "うきうきくまバルーン/yw", actioncode = "item_party_balloon_bear_yw_1106" });
            ret.Add(new ACTION_ITEM { name = "うきうきねこバルーン/bl", actioncode = "item_party_balloon_cat_bl_1106" });
            ret.Add(new ACTION_ITEM { name = "うきうきねこバルーン/pk", actioncode = "item_party_balloon_cat_pk_1106" });
            ret.Add(new ACTION_ITEM { name = "うきうきねこバルーン/yw", actioncode = "item_party_balloon_cat_yw_1106" });
            ret.Add(new ACTION_ITEM { name = "ウェルカムバルーン/bl", actioncode = "item_party_balloon_colorful_bl_1101" });
            ret.Add(new ACTION_ITEM { name = "ウェルカムバルーン/gn", actioncode = "item_party_balloon_colorful_gn_1101" });
            ret.Add(new ACTION_ITEM { name = "ウェルカムバルーン/pk", actioncode = "item_party_balloon_colorful_pk_1101" });
            ret.Add(new ACTION_ITEM { name = "ウェルカムバルーン/pr", actioncode = "item_party_balloon_colorful_pr_1101" });
            ret.Add(new ACTION_ITEM { name = "ウェルカムバルーン/rd", actioncode = "item_party_balloon_colorful_rd_1101" });
            ret.Add(new ACTION_ITEM { name = "ウェルカムバルーン/yw", actioncode = "item_party_balloon_colorful_uw_1101" });
            ret.Add(new ACTION_ITEM { name = "ウェルカムバルーン/yw", actioncode = "item_party_balloon_colorful_yw_1101" });
            ret.Add(new ACTION_ITEM { name = "ウェルカムバルーン(ハート)/bl", actioncode = "item_party_balloon_heart_bl_1101" });
            ret.Add(new ACTION_ITEM { name = "ウェルカムバルーン(ハート)/gn", actioncode = "item_party_balloon_heart_gn_1101" });
            ret.Add(new ACTION_ITEM { name = "ウェルカムバルーン(ハート)/pk", actioncode = "item_party_balloon_heart_pk_1101" });
            ret.Add(new ACTION_ITEM { name = "ウェルカムバルーン(ハート)/pr", actioncode = "item_party_balloon_heart_pr_1101" });
            ret.Add(new ACTION_ITEM { name = "ウェルカムバルーン(ハート)/rd", actioncode = "item_party_balloon_heart_rd_1101" });
            ret.Add(new ACTION_ITEM { name = "ウェルカムバルーン(ハート)/yw", actioncode = "item_party_balloon_heart_yw_1101" });
            ret.Add(new ACTION_ITEM { name = "うきうきうさぎバルーン/bl", actioncode = "item_party_balloon_rabbit_bl_1106" });
            ret.Add(new ACTION_ITEM { name = "うきうきうさぎバルーン/pk", actioncode = "item_party_balloon_rabbit_pk_1106" });
            ret.Add(new ACTION_ITEM { name = "うきうきうさぎバルーン/yw", actioncode = "item_party_balloon_rabbit_yw_1106" });
            ret.Add(new ACTION_ITEM { name = "ウェルカムバルーン(スター)/bl", actioncode = "item_party_balloon_star_bl_1101" });
            ret.Add(new ACTION_ITEM { name = "ウェルカムバルーン(スター)/gn", actioncode = "item_party_balloon_star_gn_1101" });
            ret.Add(new ACTION_ITEM { name = "ウェルカムバルーン(スター)/pk", actioncode = "item_party_balloon_star_pk_1101" });
            ret.Add(new ACTION_ITEM { name = "ウェルカムバルーン(スター)/pr", actioncode = "item_party_balloon_star_pr_1101" });
            ret.Add(new ACTION_ITEM { name = "ウェルカムバルーン(スター)/rd", actioncode = "item_party_balloon_star_rd_1101" });
            ret.Add(new ACTION_ITEM { name = "ウェルカムバルーン(スター)/yw", actioncode = "item_party_balloon_star_yw_1101" });
            ret.Add(new ACTION_ITEM { name = "ペプシバルーン", actioncode = "item_pepsi_balloon_1011" });
            ret.Add(new ACTION_ITEM { name = "ペプシペットボトル", actioncode = "item_pepsi_petbottle" });
            ret.Add(new ACTION_ITEM { name = "ペプシドリンク", actioncode = "item_pepsi_petbottle2011" });
            ret.Add(new ACTION_ITEM { name = "ブルーミスト", actioncode = "item_pw_bluemist" });
            ret.Add(new ACTION_ITEM { name = "オレンジミスト", actioncode = "item_pw_orangemist" });
            ret.Add(new ACTION_ITEM { name = "ピンクミスト", actioncode = "item_pw_pinkmist" });
            ret.Add(new ACTION_ITEM { name = "パープルミスト", actioncode = "item_pw_purplemist" });
            ret.Add(new ACTION_ITEM { name = "イエローミスト", actioncode = "item_pw_yellowmist" });
            ret.Add(new ACTION_ITEM { name = "桜クラッカー", actioncode = "item_sakura_s_cracker_1304" });
            ret.Add(new ACTION_ITEM { name = "まめまき", actioncode = "item_setsubun_beans_1101" });
            ret.Add(new ACTION_ITEM { name = "恵方巻き", actioncode = "item_setsubun_sushiroll_1101" });
            ret.Add(new ACTION_ITEM { name = "熱血のオーラが出る修造キャラメル", actioncode = "item_shuzo_caramel" });
            ret.Add(new ACTION_ITEM { name = "熱血のオーラが出る修造キャラメル２", actioncode = "item_shuzo_caramel2" });
            ret.Add(new ACTION_ITEM { name = "爽健美茶", actioncode = "item_soukenbicha_drink_action_1103" });
            ret.Add(new ACTION_ITEM { name = "シャボン玉", actioncode = "item_syabondama" });
            ret.Add(new ACTION_ITEM { name = "シャボン銃", actioncode = "item_syabonjuu" });
            ret.Add(new ACTION_ITEM { name = "熱血のオーラが出る修造キャラメル2", actioncode = "item_tvasahi_shuzo_caramel2_1107" });
            ret.Add(new ACTION_ITEM { name = "TV朝日タオルブンブン", actioncode = "item_tvasahi_syounan_towel_1106" });
            ret.Add(new ACTION_ITEM { name = "ウルトラマン ベーターカプセル", actioncode = "item_ultraman_s_betacapsule_1308" });
            ret.Add(new ACTION_ITEM { name = "綿毛飛ばし", actioncode = "item_watage_1303" });
            ret.Add(new ACTION_ITEM { name = "楽しんごのラブ注入ドリンク", actioncode = "item_yoshimoto_drink_tanoshingo_1104" });
            ret.Add(new ACTION_ITEM { name = "たこ焼き", actioncode = "item_yoyogi_takoyaki_1106" });
            ret.Add(new ACTION_ITEM { name = "ふわふわあま～い わたあめ/pk", actioncode = "item_yoyogi_wataame_pk_1106" });
            ret.Add(new ACTION_ITEM { name = "フワフワあま～い わたあめ/wh", actioncode = "item_yoyogi_wataame_wh_1106" });
            ret.Add(new ACTION_ITEM { name = "うれしい", actioncode = "joy" });
            ret.Add(new ACTION_ITEM { name = "カベチラ", actioncode = "kabechira_secret" });
            ret.Add(new ACTION_ITEM { name = "きたよ１０００万会員", actioncode = "kitayo_1000mancampaign_secret" });
            ret.Add(new ACTION_ITEM { name = "きたよ（2周年)", actioncode = "kitayo_2nd_anniversary_secret" });
            ret.Add(new ACTION_ITEM { name = "4周年記念きたよ", actioncode = "kitayo_4thAnniversary_secret" });
            ret.Add(new ACTION_ITEM { name = "きたよ１周年", actioncode = "kitayo_anniversary_secret" });
            ret.Add(new ACTION_ITEM { name = "きたよエイプリル", actioncode = "kitayo_april_secret" });
            ret.Add(new ACTION_ITEM { name = "きたよ(お外)", actioncode = "kitayo_exterior_secret" });
            ret.Add(new ACTION_ITEM { name = "きたよハロウィーン2011", actioncode = "kitayo_halloween2011_secret" });
            ret.Add(new ACTION_ITEM { name = "きたよハロウィーン2013", actioncode = "kitayo_halloween2013_secret" });
            ret.Add(new ACTION_ITEM { name = "きたよ大晦日", actioncode = "kitayo_omisoka_secret" });
            ret.Add(new ACTION_ITEM { name = "きたよ(通常)", actioncode = "kitayo_secret" });
            ret.Add(new ACTION_ITEM { name = "2012年きたよ", actioncode = "kitayo_startYear2012_secret" });
            ret.Add(new ACTION_ITEM { name = "きたよクリスマス", actioncode = "kitayo_xmas2011_secret" });
            ret.Add(new ACTION_ITEM { name = "旗を降ろす", actioncode = "kokuriko_down_flag" });
            ret.Add(new ACTION_ITEM { name = "旗を揚げる", actioncode = "kokuriko_hoist_flag" });
            ret.Add(new ACTION_ITEM { name = "水を飲む", actioncode = "kokuriko_mizunuma" });
            ret.Add(new ACTION_ITEM { name = "ポーズ", actioncode = "kokuriko_shun" });
            ret.Add(new ACTION_ITEM { name = "手をふる", actioncode = "kokuriko_umi" });
            ret.Add(new ACTION_ITEM { name = "小股", actioncode = "komata" });
            ret.Add(new ACTION_ITEM { name = "小股エンド", actioncode = "komata_end" });
            ret.Add(new ACTION_ITEM { name = "上がる", actioncode = "kyon_b" });
            ret.Add(new ACTION_ITEM { name = "でかマム", actioncode = "maximum_secret" });
            ret.Add(new ACTION_ITEM { name = "ミニマム", actioncode = "minimum_secret" });
            ret.Add(new ACTION_ITEM { name = "投げ出される", actioncode = "missreturn" });
            ret.Add(new ACTION_ITEM { name = "魔女の鍋", actioncode = "mixpot_1410" });
            ret.Add(new ACTION_ITEM { name = "うれしい（ゆっくり）", actioncode = "moonAction" });
            ret.Add(new ACTION_ITEM { name = "浮かぶ歩く", actioncode = "moonRun" });
            ret.Add(new ACTION_ITEM { name = "猫ジョイ", actioncode = "neko_joy" });
            ret.Add(new ACTION_ITEM { name = "「Sweet Season」アクション", actioncode = "neta_avex_hamasaki_sweetseason_1104" });
            ret.Add(new ACTION_ITEM { name = "バニーポーズ", actioncode = "neta_bunnypose" });
            ret.Add(new ACTION_ITEM { name = "チャンバラ", actioncode = "neta_chanbara" });
            ret.Add(new ACTION_ITEM { name = "千鳥足", actioncode = "neta_chidoriashi" });
            ret.Add(new ACTION_ITEM { name = "アイアムチョーノ", actioncode = "neta_chono" });
            ret.Add(new ACTION_ITEM { name = "蝶野２", actioncode = "neta_chono2" });
            ret.Add(new ACTION_ITEM { name = "コスメ(男)", actioncode = "neta_cosme_boy" });
            ret.Add(new ACTION_ITEM { name = "コスメ女子", actioncode = "neta_cosme_girl" });
            ret.Add(new ACTION_ITEM { name = "エネミーアタック", actioncode = "neta_enemyattack" });
            ret.Add(new ACTION_ITEM { name = "ビクビク", actioncode = "neta_event_4th_bikubiku" });
            ret.Add(new ACTION_ITEM { name = "ゆっくり回る", actioncode = "neta_event_4th_downRope" });
            ret.Add(new ACTION_ITEM { name = "笑顔で座る", actioncode = "neta_event_4th_suberiDai" });
            ret.Add(new ACTION_ITEM { name = "笑顔で座って渡す", actioncode = "neta_event_4th_suberiDaiOut" });
            ret.Add(new ACTION_ITEM { name = "４周年トランポリン", actioncode = "neta_event_4th_trampoline" });
            ret.Add(new ACTION_ITEM { name = "横歩き", actioncode = "neta_event_4th_yokoAruki" });
            ret.Add(new ACTION_ITEM { name = "顔 煙", actioncode = "neta_event_apf" });
            ret.Add(new ACTION_ITEM { name = "全体 煙", actioncode = "neta_event_apf2014" });
            ret.Add(new ACTION_ITEM { name = "変身", actioncode = "neta_event_apf2015" });
            ret.Add(new ACTION_ITEM { name = "お化けを捕まえる", actioncode = "neta_event_capture_ghost_secret" });
            ret.Add(new ACTION_ITEM { name = "魔法陣に入る", actioncode = "neta_event_enterBook" });
            ret.Add(new ACTION_ITEM { name = "本の中に入る/魔法陣から出る", actioncode = "neta_event_enterBook_secret" });
            ret.Add(new ACTION_ITEM { name = "魔法陣をでる", actioncode = "neta_event_exist" });
            ret.Add(new ACTION_ITEM { name = "魔法陣をでる２０１５", actioncode = "neta_event_exist_hw2015" });
            ret.Add(new ACTION_ITEM { name = "魔法陣をでるノーマル２０１", actioncode = "neta_event_exist_hw2015_normal" });
            ret.Add(new ACTION_ITEM { name = "魔法陣から出る", actioncode = "neta_event_exist_secret" });
            ret.Add(new ACTION_ITEM { name = "本の中から出る", actioncode = "neta_event_existBook" });
            ret.Add(new ACTION_ITEM { name = "本の中から出る", actioncode = "neta_event_existBook_secret" });
            ret.Add(new ACTION_ITEM { name = "おばけワシャワシャ", actioncode = "neta_event_ghost_washawasha_secret" });
            ret.Add(new ACTION_ITEM { name = "ステージクリア", actioncode = "neta_event_goal1" });
            ret.Add(new ACTION_ITEM { name = "ゴール", actioncode = "neta_event_goal2" });
            ret.Add(new ACTION_ITEM { name = "クルクル", actioncode = "neta_event_kurukuru" });
            ret.Add(new ACTION_ITEM { name = "プレイプラン", actioncode = "neta_event_playPlane" });
            ret.Add(new ACTION_ITEM { name = "矢印カードを引く_trump", actioncode = "neta_event_playPlane_3rdstage_trump_secret" });
            ret.Add(new ACTION_ITEM { name = "矢印カードを引く_short", actioncode = "neta_event_playPlane_alice3_secret" });
            ret.Add(new ACTION_ITEM { name = "矢印カードを引く_Long", actioncode = "neta_event_playPlane_long_secret" });
            ret.Add(new ACTION_ITEM { name = "矢印カードを引く_queen", actioncode = "neta_event_playPlane_queen_secret" });
            ret.Add(new ACTION_ITEM { name = "矢印カードを引く_Normal", actioncode = "neta_event_playPlane_secret" });
            ret.Add(new ACTION_ITEM { name = "泳ぐ", actioncode = "neta_event_seaDive_suisui" });
            ret.Add(new ACTION_ITEM { name = "泳ぐA", actioncode = "neta_event_seaDive_suisuiA" });
            ret.Add(new ACTION_ITEM { name = "泳ぐAエンド", actioncode = "neta_event_seaDive_suisuiAend" });
            ret.Add(new ACTION_ITEM { name = "泳ぐエアー", actioncode = "neta_event_seaDive_suisuiAir" });
            ret.Add(new ACTION_ITEM { name = "泳ぐAとB", actioncode = "neta_event_seaDive_suisuiAtoB" });
            ret.Add(new ACTION_ITEM { name = "泳ぐAとD", actioncode = "neta_event_seaDive_suisuiAtoD" });
            ret.Add(new ACTION_ITEM { name = "泳ぐB", actioncode = "neta_event_seaDive_suisuiB" });
            ret.Add(new ACTION_ITEM { name = "泳ぐBエンド", actioncode = "neta_event_seaDive_suisuiBend" });
            ret.Add(new ACTION_ITEM { name = "泳ぐBとA", actioncode = "neta_event_seaDive_suisuiBtoA" });
            ret.Add(new ACTION_ITEM { name = "回転", actioncode = "neta_event_seaDive_suisuiBtoB" });
            ret.Add(new ACTION_ITEM { name = "泳ぐBとC", actioncode = "neta_event_seaDive_suisuiBtoC" });
            ret.Add(new ACTION_ITEM { name = "泳ぐBとD", actioncode = "neta_event_seaDive_suisuiBtoD" });
            ret.Add(new ACTION_ITEM { name = "泳ぐC", actioncode = "neta_event_seaDive_suisuiC" });
            ret.Add(new ACTION_ITEM { name = "泳ぐCエンド", actioncode = "neta_event_seaDive_suisuiCend" });
            ret.Add(new ACTION_ITEM { name = "泳ぐCとB", actioncode = "neta_event_seaDive_suisuiCtoB" });
            ret.Add(new ACTION_ITEM { name = "泳ぐD", actioncode = "neta_event_seaDive_suisuiD" });
            ret.Add(new ACTION_ITEM { name = "泳ぐDエンド", actioncode = "neta_event_seaDive_suisuiDend" });
            ret.Add(new ACTION_ITEM { name = "泳ぐDとA", actioncode = "neta_event_seaDive_suisuiDtoA" });
            ret.Add(new ACTION_ITEM { name = "泳ぐDとB", actioncode = "neta_event_seaDive_suisuiDtoB" });
            ret.Add(new ACTION_ITEM { name = "泳ぐDとD", actioncode = "neta_event_seaDive_suisuiDtoD" });
            ret.Add(new ACTION_ITEM { name = "上に上がる", actioncode = "neta_event_seaDive_suisuiDtoE" });
            ret.Add(new ACTION_ITEM { name = "泳ぐE", actioncode = "neta_event_seaDive_suisuiE" });
            ret.Add(new ACTION_ITEM { name = "泳ぐEエンド", actioncode = "neta_event_seaDive_suisuiEend" });
            ret.Add(new ACTION_ITEM { name = "泳ぐEとD", actioncode = "neta_event_seaDive_suisuiEtoD" });
            ret.Add(new ACTION_ITEM { name = "魚にぶつかる", actioncode = "neta_event_seaDive_suisuiHit" });
            ret.Add(new ACTION_ITEM { name = "わわわ！", actioncode = "neta_event_spider_downRope" });
            ret.Add(new ACTION_ITEM { name = "わわわ！座る", actioncode = "neta_event_spider_downRope2" });
            ret.Add(new ACTION_ITEM { name = "フラフラ", actioncode = "neta_event_spider_furafura" });
            ret.Add(new ACTION_ITEM { name = "震える", actioncode = "neta_eventStorm1_action" });
            ret.Add(new ACTION_ITEM { name = "とったどー！", actioncode = "neta_fishing_tottado" });
            ret.Add(new ACTION_ITEM { name = "とったどー！2012", actioncode = "neta_fishing_tottado_2012" });
            ret.Add(new ACTION_ITEM { name = "neta_g1_zabuton", actioncode = "neta_g1_zabuton" });
            ret.Add(new ACTION_ITEM { name = "座布団投げ", actioncode = "neta_g1_zabuton_secret" });
            ret.Add(new ACTION_ITEM { name = "ゴセイブラックの決めポーズ", actioncode = "neta_gosei_black" });
            ret.Add(new ACTION_ITEM { name = "ゴセイブルー", actioncode = "neta_gosei_blue" });
            ret.Add(new ACTION_ITEM { name = "ゴセイピンクの決めポーズ", actioncode = "neta_gosei_pink" });
            ret.Add(new ACTION_ITEM { name = "ゴセイレッド", actioncode = "neta_gosei_red" });
            ret.Add(new ACTION_ITEM { name = "ゴセイイエローの決めポーズ", actioncode = "neta_gosei_yellow" });
            ret.Add(new ACTION_ITEM { name = "FUJIWARA･原西　友達", actioncode = "neta_haranishi_friend_1302" });
            ret.Add(new ACTION_ITEM { name = "原西なるほど", actioncode = "neta_haranishi_naruhodo_1302" });
            ret.Add(new ACTION_ITEM { name = "原西多数決", actioncode = "neta_haranishi_tasuketsu_1302" });
            ret.Add(new ACTION_ITEM { name = "FUJIWARA･原西　とんち", actioncode = "neta_haranishi_tonchi_1302" });
            ret.Add(new ACTION_ITEM { name = "時は来た", actioncode = "neta_hashimoto" });
            ret.Add(new ACTION_ITEM { name = "ヒーローアタック", actioncode = "neta_heroattack" });
            ret.Add(new ACTION_ITEM { name = "ジャグリング", actioncode = "neta_juggling" });
            ret.Add(new ACTION_ITEM { name = "カンペ拍手", actioncode = "neta_kanpe_hakushu" });
            ret.Add(new ACTION_ITEM { name = "カンペ；落ちます", actioncode = "neta_kanpe_leave" });
            ret.Add(new ACTION_ITEM { name = "カンペ：まいて！", actioncode = "neta_kanpe_maite" });
            ret.Add(new ACTION_ITEM { name = "KARAのヒップダンス", actioncode = "neta_kara_dance" });
            ret.Add(new ACTION_ITEM { name = "そんなのかんけいねー", actioncode = "neta_kojima_kankeine" });
            ret.Add(new ACTION_ITEM { name = "軽く拍手", actioncode = "neta_kokuriko_shake_hands_secret" });
            ret.Add(new ACTION_ITEM { name = "漫才アクション（ツッコミあり）", actioncode = "neta_manzai" });
            ret.Add(new ACTION_ITEM { name = "漫才アクション（ツッコミなし）", actioncode = "neta_manzai_not" });
            ret.Add(new ACTION_ITEM { name = "もちつき", actioncode = "neta_mochituki" });
            ret.Add(new ACTION_ITEM { name = "プロレスLOVE", actioncode = "neta_muto" });
            ret.Add(new ACTION_ITEM { name = "ゼァッ!", actioncode = "neta_nagata" });
            ret.Add(new ACTION_ITEM { name = "なんでやねん", actioncode = "neta_nandeyanen" });
            ret.Add(new ACTION_ITEM { name = "ひぐちカッター", actioncode = "neta_ofc_hige_cutter" });
            ret.Add(new ACTION_ITEM { name = "加藤茶くしゃみ", actioncode = "neta_ofc_katoucha_kushami" });
            ret.Add(new ACTION_ITEM { name = "加藤茶のちょっとだけよ", actioncode = "neta_ofc_katoucha_tyottodakeyo" });
            ret.Add(new ACTION_ITEM { name = "そんなの関係ねえ", actioncode = "neta_ofc_kojima_kankeine" });
            ret.Add(new ACTION_ITEM { name = "おっぱっぴー", actioncode = "neta_ofc_kojima_opapi" });
            ret.Add(new ACTION_ITEM { name = "ゲッツ", actioncode = "neta_ofc_sakano_gets" });
            ret.Add(new ACTION_ITEM { name = "おしりペンペン", actioncode = "neta_oshiripenen" });
            ret.Add(new ACTION_ITEM { name = "モデルウォーク", actioncode = "neta_parisFashion" });
            ret.Add(new ACTION_ITEM { name = "イエイ", actioncode = "neta_player_fever" });
            ret.Add(new ACTION_ITEM { name = "ライダー", actioncode = "neta_rider" });
            ret.Add(new ACTION_ITEM { name = "俺！参上！", actioncode = "neta_rider_denou" });
            ret.Add(new ACTION_ITEM { name = "ライダージャンプ", actioncode = "neta_rider_shodai" });
            ret.Add(new ACTION_ITEM { name = "イー！！", actioncode = "neta_rider_shoker" });
            ret.Add(new ACTION_ITEM { name = "金メダル！", actioncode = "neta_saiten_gold" });
            ret.Add(new ACTION_ITEM { name = "ジャンプ！", actioncode = "neta_saiten_jump" });
            ret.Add(new ACTION_ITEM { name = "ノーミス！", actioncode = "neta_saiten_nomiss" });
            ret.Add(new ACTION_ITEM { name = "世界一！", actioncode = "neta_saiten_world" });
            ret.Add(new ACTION_ITEM { name = "採点０点", actioncode = "neta_saiten0" });
            ret.Add(new ACTION_ITEM { name = "採点１０点", actioncode = "neta_saiten10" });
            ret.Add(new ACTION_ITEM { name = "採点３０００点", actioncode = "neta_saiten3000" });
            ret.Add(new ACTION_ITEM { name = "採点（5点）", actioncode = "neta_saiten5" });
            ret.Add(new ACTION_ITEM { name = "敬礼", actioncode = "neta_salute" });
            ret.Add(new ACTION_ITEM { name = "志村けんのアイ～ン", actioncode = "neta_shimura_ain" });
            ret.Add(new ACTION_ITEM { name = "アイーン体操　メインver", actioncode = "neta_shimura_ain_2012_1201" });
            ret.Add(new ACTION_ITEM { name = "アイーン体操　幸せいっぱい朝が来た♪ver", actioncode = "neta_shimura_ain_exercise_1201" });
            ret.Add(new ACTION_ITEM { name = "変なおじさん（ver.１）", actioncode = "neta_shimura_hennaojisan1" });
            ret.Add(new ACTION_ITEM { name = "変なおじさん（ver.２）", actioncode = "neta_shimura_hennaojisan2" });
            ret.Add(new ACTION_ITEM { name = "変なおじさん（ver.３）", actioncode = "neta_shimura_hennaojisan3" });
            ret.Add(new ACTION_ITEM { name = "neta_spaceMoonFlag", actioncode = "neta_spaceMoonFlag" });
            ret.Add(new ACTION_ITEM { name = "宇宙旗を立てる", actioncode = "neta_spaceMoonFlag_secret" });
            ret.Add(new ACTION_ITEM { name = "ムーンジェット", actioncode = "neta_spaceMoonJet" });
            ret.Add(new ACTION_ITEM { name = "ムーンジェット", actioncode = "neta_spaceMoonJet_secret" });
            ret.Add(new ACTION_ITEM { name = "回転する", actioncode = "neta_spaceMoonRolling" });
            ret.Add(new ACTION_ITEM { name = "neta_spaceShuttleDrink", actioncode = "neta_spaceShuttleDrink" });
            ret.Add(new ACTION_ITEM { name = "宇宙水を飲む", actioncode = "neta_spaceShuttleDrink_secret" });
            ret.Add(new ACTION_ITEM { name = "neta_spaceShuttleRolling", actioncode = "neta_spaceShuttleRolling" });
            ret.Add(new ACTION_ITEM { name = "宇宙爆バク転", actioncode = "neta_spaceShuttleRolling_secret" });
            ret.Add(new ACTION_ITEM { name = "横にする", actioncode = "neta_spider_DownJamp" });
            ret.Add(new ACTION_ITEM { name = "2回転", actioncode = "neta_spider_DownJampRot" });
            ret.Add(new ACTION_ITEM { name = "回転する", actioncode = "neta_spider_ropeUp" });
            ret.Add(new ACTION_ITEM { name = "愛してま～す！", actioncode = "neta_tana" });
            ret.Add(new ACTION_ITEM { name = "うっふん", actioncode = "neta_uffun" });
            ret.Add(new ACTION_ITEM { name = "顔だけゆれる", actioncode = "neta_vj_audience_dance" });
            ret.Add(new ACTION_ITEM { name = "ニコ", actioncode = "neta_vj_audience_dance_joy" });
            ret.Add(new ACTION_ITEM { name = "VJダンススイング", actioncode = "neta_vj_audience_dance_swing" });
            ret.Add(new ACTION_ITEM { name = "ゆれる", actioncode = "neta_vj_player_exciting" });
            ret.Add(new ACTION_ITEM { name = "やれやれ", actioncode = "neta_yareyare" });
            ret.Add(new ACTION_ITEM { name = "YO！", actioncode = "neta_yo" });
            ret.Add(new ACTION_ITEM { name = "数を数える男のギューン", actioncode = "neta_yoshimoto_gyuun_1105" });
            ret.Add(new ACTION_ITEM { name = "品川庄司　庄司の平成のパピプペポ", actioncode = "neta_yoshimoto_shoji_1104" });
            ret.Add(new ACTION_ITEM { name = "ズッコケ", actioncode = "neta_yoshimoto_zukkoke_1105" });
            ret.Add(new ACTION_ITEM { name = "ngsun_1206", actioncode = "ngsun_1206" });
            ret.Add(new ACTION_ITEM { name = "nice_event", actioncode = "nice_event" });
            ret.Add(new ACTION_ITEM { name = "ナイスイベント", actioncode = "nice_event_secret" });
            ret.Add(new ACTION_ITEM { name = "ずっきゅーん♥", actioncode = "overreaction_heart" });
            ret.Add(new ACTION_ITEM { name = "キメ顔", actioncode = "overreaction_kimegao" });
            ret.Add(new ACTION_ITEM { name = "キラーン", actioncode = "overreaction_kiran" });
            ret.Add(new ACTION_ITEM { name = "驚愕", actioncode = "overreaction_kyougaku" });
            ret.Add(new ACTION_ITEM { name = "ムカッ！", actioncode = "overreaction_muka" });
            ret.Add(new ACTION_ITEM { name = "しーん･･･", actioncode = "overreaction_quiet" });
            ret.Add(new ACTION_ITEM { name = "感染廃病院ビックリアクション", actioncode = "overreaction_scream" });
            ret.Add(new ACTION_ITEM { name = "ガビーン", actioncode = "overreaction_shock" });
            ret.Add(new ACTION_ITEM { name = "大笑い", actioncode = "overreaction_smile" });
            ret.Add(new ACTION_ITEM { name = "てへぺろ", actioncode = "overreaction_tehepero" });
            ret.Add(new ACTION_ITEM { name = "うるうる", actioncode = "overreaction_uruuru" });
            ret.Add(new ACTION_ITEM { name = "スキル･バズーカ", actioncode = "party_skill_bazooka" });
            ret.Add(new ACTION_ITEM { name = "ペナルティラン", actioncode = "penaltyRun" });
            ret.Add(new ACTION_ITEM { name = "ペットと遊ぶ", actioncode = "pet_ball" });
            ret.Add(new ACTION_ITEM { name = "ボールを投げる", actioncode = "pet_ball2" });
            ret.Add(new ACTION_ITEM { name = "だっこする", actioncode = "pet_dakko" });
            ret.Add(new ACTION_ITEM { name = "回転", actioncode = "pet_flip" });
            ret.Add(new ACTION_ITEM { name = "ペットを投げる", actioncode = "pet_high_jump" });
            ret.Add(new ACTION_ITEM { name = "じゃらす", actioncode = "pet_jarasu" });
            ret.Add(new ACTION_ITEM { name = "ペットを投げる", actioncode = "pet_jump" });
            ret.Add(new ACTION_ITEM { name = "ペットとクルクル", actioncode = "pet_kurukuru" });
            ret.Add(new ACTION_ITEM { name = "くるくる", actioncode = "pet_kurukuruair" });
            ret.Add(new ACTION_ITEM { name = "ペットを掃除する", actioncode = "pet_migaku" });
            ret.Add(new ACTION_ITEM { name = "ペットをなでる", actioncode = "pet_nade" });
            ret.Add(new ACTION_ITEM { name = "乗る", actioncode = "pet_noru" });
            ret.Add(new ACTION_ITEM { name = "おて", actioncode = "pet_ote" });
            ret.Add(new ACTION_ITEM { name = "ペットに乗る", actioncode = "pet_ride" });
            ret.Add(new ACTION_ITEM { name = "ペット投げる", actioncode = "pet_ultra_c" });
            ret.Add(new ACTION_ITEM { name = "ピクシーラン", actioncode = "pixieRun" });
            ret.Add(new ACTION_ITEM { name = "ピザを置く", actioncode = "pizza_push" });
            ret.Add(new ACTION_ITEM { name = "ピザを受け取る", actioncode = "pizza_pushpull" });
            ret.Add(new ACTION_ITEM { name = "ピザ配達", actioncode = "pizza_run" });
            ret.Add(new ACTION_ITEM { name = "ピザをもって走る", actioncode = "pizza_run2" });
            ret.Add(new ACTION_ITEM { name = "ピザを詰める", actioncode = "pizza_take2" });
            ret.Add(new ACTION_ITEM { name = "華麗なスケーティング", actioncode = "ports_gracefulSkate" });
            ret.Add(new ACTION_ITEM { name = "水たまりでピチャピチャ", actioncode = "rainy_extr_pool_1406" });
            ret.Add(new ACTION_ITEM { name = "手を上げる", actioncode = "rainy_umbrella_joy" });
            ret.Add(new ACTION_ITEM { name = "歩く", actioncode = "rainy_umbrella_run_komata" });
            ret.Add(new ACTION_ITEM { name = "腰をずらす", actioncode = "rainy_umbrella_run_suriashi" });
            ret.Add(new ACTION_ITEM { name = "手を胸にやる", actioncode = "rainy_umbrella_stand" });
            ret.Add(new ACTION_ITEM { name = "ばんざ～いｗ", actioncode = "ranaruta" });
            ret.Add(new ACTION_ITEM { name = "浮く", actioncode = "ride_casinobike" });
            ret.Add(new ACTION_ITEM { name = "エスカ・ホイールの座るアクション", actioncode = "ride_casinobikeFeedEnd" });
            ret.Add(new ACTION_ITEM { name = "ローラー", actioncode = "ride_casinorollerblade_A" });
            ret.Add(new ACTION_ITEM { name = "ローラー2", actioncode = "ride_casinorollerblade_B" });
            ret.Add(new ACTION_ITEM { name = "横向く", actioncode = "ride_skateboard" });
            ret.Add(new ACTION_ITEM { name = "スケートボードを漕ぐ", actioncode = "ride_skateboardFeed" });
            ret.Add(new ACTION_ITEM { name = "ﾌｯ!", actioncode = "ringin" });
            ret.Add(new ACTION_ITEM { name = "歩行アクション", actioncode = "run" });
            ret.Add(new ACTION_ITEM { name = "歩く", actioncode = "run_komata" });
            ret.Add(new ACTION_ITEM { name = "小股で走るエンド", actioncode = "run_komata_end" });
            ret.Add(new ACTION_ITEM { name = "走る忍者", actioncode = "run_ninja" });
            ret.Add(new ACTION_ITEM { name = "すりあし", actioncode = "run_suriashi" });
            ret.Add(new ACTION_ITEM { name = "かなしい", actioncode = "sad" });
            ret.Add(new ACTION_ITEM { name = "ハンド", actioncode = "shake_hand" });
            ret.Add(new ACTION_ITEM { name = "忍び足", actioncode = "shinobiashi_1501" });
            ret.Add(new ACTION_ITEM { name = "しりもち", actioncode = "shirimochi" });
            ret.Add(new ACTION_ITEM { name = "書道 終わり", actioncode = "shodo_end" });
            ret.Add(new ACTION_ITEM { name = "書道 座る", actioncode = "shodo_sit" });
            ret.Add(new ACTION_ITEM { name = "書道 座り直す", actioncode = "shodo_sit_reload" });
            ret.Add(new ACTION_ITEM { name = "書道 始め", actioncode = "shodo_start" });
            ret.Add(new ACTION_ITEM { name = "書道 書いている", actioncode = "shodo_write" });
            ret.Add(new ACTION_ITEM { name = "座る", actioncode = "sit" });
            ret.Add(new ACTION_ITEM { name = "おなら", actioncode = "sit_furniture_onara" });
            ret.Add(new ACTION_ITEM { name = "足の骨を折る", actioncode = "sit_seiza" });
            ret.Add(new ACTION_ITEM { name = "スケートアクション", actioncode = "skate" });
            ret.Add(new ACTION_ITEM { name = "寝る", actioncode = "sleep_secret" });
            ret.Add(new ACTION_ITEM { name = "スノーホワイト", actioncode = "snowwhite_well_1503" });
            ret.Add(new ACTION_ITEM { name = "ドリブル", actioncode = "soccer_dribble" });
            ret.Add(new ACTION_ITEM { name = "サッカードリブル2011", actioncode = "soccer_dribble2011" });
            ret.Add(new ACTION_ITEM { name = "泳ぐ", actioncode = "spaceAction" });
            ret.Add(new ACTION_ITEM { name = "宙に浮く", actioncode = "spaceRun" });
            ret.Add(new ACTION_ITEM { name = "足を広げる", actioncode = "spaceSwim" });
            ret.Add(new ACTION_ITEM { name = "落ちる", actioncode = "spf_down" });
            ret.Add(new ACTION_ITEM { name = "落ちる2", actioncode = "spf_downEnd" });
            ret.Add(new ACTION_ITEM { name = "巨人ダウンストップ", actioncode = "spf_downStop" });
            ret.Add(new ACTION_ITEM { name = "巨人ジャンプエンド", actioncode = "spf_jumpEnd" });
            ret.Add(new ACTION_ITEM { name = "回る", actioncode = "spf_jumpStart" });
            ret.Add(new ACTION_ITEM { name = "巨人ラン", actioncode = "spf_npc_appear_run" });
            ret.Add(new ACTION_ITEM { name = "おっとっと", actioncode = "spf_ottotto" });
            ret.Add(new ACTION_ITEM { name = "エレンジャンプ", actioncode = "spf_shingeki_game_eren_jumpStart" });
            ret.Add(new ACTION_ITEM { name = "巨人ゲームジャンプエンド", actioncode = "spf_shingeki_game_jumpEnd" });
            ret.Add(new ACTION_ITEM { name = "回ったりする", actioncode = "spf_shingeki_game_jumpReturn" });
            ret.Add(new ACTION_ITEM { name = "くるくる回る", actioncode = "spf_shingeki_game_jumpStart" });
            ret.Add(new ACTION_ITEM { name = "巨人みかさジャンプスタート", actioncode = "spf_shingeki_game_mikasa_jumpStart" });
            ret.Add(new ACTION_ITEM { name = "回る", actioncode = "spf_shingeki_game_npc_apper_jumpEnd" });
            ret.Add(new ACTION_ITEM { name = "飛ぶ", actioncode = "spf_shingeki_game_wallDown" });
            ret.Add(new ACTION_ITEM { name = "1回転ジャンプ", actioncode = "spf_shingeki_game_wallJump1" });
            ret.Add(new ACTION_ITEM { name = "進撃 回る", actioncode = "spf_shingeki_game_wallJump2" });
            ret.Add(new ACTION_ITEM { name = "巨人ジャンプエンド１６", actioncode = "spf_shingeki_jumpEnd16" });
            ret.Add(new ACTION_ITEM { name = "巨人ジャンプエンド３２", actioncode = "spf_shingeki_jumpEnd32" });
            ret.Add(new ACTION_ITEM { name = "巨人ジャンプエンド４８", actioncode = "spf_shingeki_jumpEnd48" });
            ret.Add(new ACTION_ITEM { name = "巨人ジャンプスタート１６", actioncode = "spf_shingeki_jumpStart16" });
            ret.Add(new ACTION_ITEM { name = "巨人ジャンプスタート３２", actioncode = "spf_shingeki_jumpStart32" });
            ret.Add(new ACTION_ITEM { name = "巨人ジャンプスタート４８", actioncode = "spf_shingeki_jumpStart48" });
            ret.Add(new ACTION_ITEM { name = "壁をける", actioncode = "spf_titaneren_appear_jump" });
            ret.Add(new ACTION_ITEM { name = "叫ぶ", actioncode = "spf_titaneren_appear_jump_end" });
            ret.Add(new ACTION_ITEM { name = "走る走る俺たち", actioncode = "spf_titaneren_appear_run" });
            ret.Add(new ACTION_ITEM { name = "ポーズ", actioncode = "spf_titaneren_attack_jump" });
            ret.Add(new ACTION_ITEM { name = "走ってジャンプ", actioncode = "spf_titaneren_disappear_jump" });
            ret.Add(new ACTION_ITEM { name = "３回転ジャンプ", actioncode = "sports_1080turn" });
            ret.Add(new ACTION_ITEM { name = "４回転ジャンプ", actioncode = "sports_1440turn" });
            ret.Add(new ACTION_ITEM { name = "４回転ジャンプおっとっと", actioncode = "sports_1440turnFail" });
            ret.Add(new ACTION_ITEM { name = "１回転ジャンプ", actioncode = "sports_360turn" });
            ret.Add(new ACTION_ITEM { name = "ケンカキック", actioncode = "sports_893k" });
            ret.Add(new ACTION_ITEM { name = "荒川静香のイナバウアー", actioncode = "sports_arakawa_inaBauer" });
            ret.Add(new ACTION_ITEM { name = "バク転", actioncode = "sports_backflip" });
            ret.Add(new ACTION_ITEM { name = "バク宙", actioncode = "sports_bakuchu" });
            ret.Add(new ACTION_ITEM { name = "バク宙おっとっと", actioncode = "sports_bakuchuFail" });
            ret.Add(new ACTION_ITEM { name = "初心者のスケーティング", actioncode = "sports_beginnerSkate" });
            ret.Add(new ACTION_ITEM { name = "ビールマンスピン", actioncode = "sports_biellmann" });
            ret.Add(new ACTION_ITEM { name = "バランス", actioncode = "sports_blance" });
            ret.Add(new ACTION_ITEM { name = "方向転換", actioncode = "sports_changeDir" });
            ret.Add(new ACTION_ITEM { name = "ぐるぐるラリアット", actioncode = "sports_chosyu_guruguru" });
            ret.Add(new ACTION_ITEM { name = "長州力の入場シーン", actioncode = "sports_chosyu_nyujo" });
            ret.Add(new ACTION_ITEM { name = "カラリアット", actioncode = "sports_chosyu_rari" });
            ret.Add(new ACTION_ITEM { name = "ストンピング", actioncode = "sports_chosyu_stomping" });
            ret.Add(new ACTION_ITEM { name = "バットマン", actioncode = "sports_curvydance_batman" });
            ret.Add(new ACTION_ITEM { name = "バットマンアイテムアニメーション", actioncode = "sports_curvydance_batman_itemAnimation" });
            ret.Add(new ACTION_ITEM { name = "育てよう私のCカーブ", actioncode = "sports_curvydance_c_curve" });
            ret.Add(new ACTION_ITEM { name = "こっちにいくけど戻っちゃう", actioncode = "sports_curvydance_modocchau" });
            ret.Add(new ACTION_ITEM { name = "ゆら～ゆら～", actioncode = "sports_curvydance_yurayura" });
            ret.Add(new ACTION_ITEM { name = "華麗なスケーティング", actioncode = "sports_gracefulSkate" });
            ret.Add(new ACTION_ITEM { name = "スパイラル", actioncode = "sports_hangleg" });
            ret.Add(new ACTION_ITEM { name = "シューティングスタープレス", actioncode = "sports_ibushi_press" });
            ret.Add(new ACTION_ITEM { name = "飯伏乱舞", actioncode = "sports_ibushi_ranbu" });
            ret.Add(new ACTION_ITEM { name = "イナバウアー", actioncode = "sports_inaBauer" });
            ret.Add(new ACTION_ITEM { name = "１，２，３、ダー！！", actioncode = "sports_inoki_123" });
            ret.Add(new ACTION_ITEM { name = "sports_inoki_123_npc", actioncode = "sports_inoki_123_npc" });
            ret.Add(new ACTION_ITEM { name = "闘魂注入ビンタ", actioncode = "sports_inoki_binta" });
            ret.Add(new ACTION_ITEM { name = "ダー！！", actioncode = "sports_inoki_da" });
            ret.Add(new ACTION_ITEM { name = "ジタバタ", actioncode = "sports_jitabata" });
            ret.Add(new ACTION_ITEM { name = "いっちゃうぞバカヤロー", actioncode = "sports_kojima_elbow" });
            ret.Add(new ACTION_ITEM { name = "ひじあたっく", actioncode = "sports_kojima_npc_elbow" });
            ret.Add(new ACTION_ITEM { name = "絶対に落とせない初級リフティング", actioncode = "sports_liftingMiddle" });
            ret.Add(new ACTION_ITEM { name = "絶対に落とせない初級リフティング", actioncode = "sports_liftingMiddle2011" });
            ret.Add(new ACTION_ITEM { name = "天才レフティの片足リフティング", actioncode = "sports_liftingNormal" });
            ret.Add(new ACTION_ITEM { name = "絶対に落とせないスペシャルリフティング", actioncode = "sports_liftingSpecial" });
            ret.Add(new ACTION_ITEM { name = "前ならえ", actioncode = "sports_maenarae" });
            ret.Add(new ACTION_ITEM { name = "先頭前ならえ", actioncode = "sports_maenaraelead" });
            ret.Add(new ACTION_ITEM { name = "餅つきチョップ", actioncode = "sports_mochitsuki" });
            ret.Add(new ACTION_ITEM { name = "モンゴリアンチョップ", actioncode = "sports_mongolian" });
            ret.Add(new ACTION_ITEM { name = "永田ダンス", actioncode = "sports_nagata_nagadance_1208" });
            ret.Add(new ACTION_ITEM { name = "くねくねボマイェ", actioncode = "sports_nakamura_kunekune_1208" });
            ret.Add(new ACTION_ITEM { name = "レッド・シューズ海野「カウント2.9」", actioncode = "sports_redshoes_29count_1308" });
            ret.Add(new ACTION_ITEM { name = "レッド・シューズ海野「カウント3.0」", actioncode = "sports_redshoes_30count_1308" });
            ret.Add(new ACTION_ITEM { name = "連環拳 一、起勢", actioncode = "sports_renkanken_00" });
            ret.Add(new ACTION_ITEM { name = "連環拳 二、擱手衝拳", actioncode = "sports_renkanken_01" });
            ret.Add(new ACTION_ITEM { name = "連環拳 三、弾腿衝拳", actioncode = "sports_renkanken_02" });
            ret.Add(new ACTION_ITEM { name = "連環拳 四、馬歩架打", actioncode = "sports_renkanken_03" });
            ret.Add(new ACTION_ITEM { name = "連環拳 五、截把", actioncode = "sports_renkanken_04" });
            ret.Add(new ACTION_ITEM { name = "連環拳 六、鷂子翻身", actioncode = "sports_renkanken_05" });
            ret.Add(new ACTION_ITEM { name = "連環拳 七、連環掌", actioncode = "sports_renkanken_06" });
            ret.Add(new ACTION_ITEM { name = "連環拳 八、回頭劈掌", actioncode = "sports_renkanken_07" });
            ret.Add(new ACTION_ITEM { name = "連環拳 九、弓歩穿掌", actioncode = "sports_renkanken_08" });
            ret.Add(new ACTION_ITEM { name = "連環拳 十、燕子抄水", actioncode = "sports_renkanken_09" });
            ret.Add(new ACTION_ITEM { name = "連環拳 十一、斜形", actioncode = "sports_renkanken_10" });
            ret.Add(new ACTION_ITEM { name = "連環拳 十二、?脚迎面掌", actioncode = "sports_renkanken_11" });
            ret.Add(new ACTION_ITEM { name = "連環拳 十三、転身架打", actioncode = "sports_renkanken_12" });
            ret.Add(new ACTION_ITEM { name = "連環拳 十四、狠脚双衝拳", actioncode = "sports_renkanken_13" });
            ret.Add(new ACTION_ITEM { name = "連環拳 十五、踩脚頂肘", actioncode = "sports_renkanken_14" });
            ret.Add(new ACTION_ITEM { name = "連環拳 十六、転身圧掌", actioncode = "sports_renkanken_15" });
            ret.Add(new ACTION_ITEM { name = "連環拳 十七、退歩抜剣", actioncode = "sports_renkanken_16" });
            ret.Add(new ACTION_ITEM { name = "連環拳 十八、虚歩坐山", actioncode = "sports_renkanken_17" });
            ret.Add(new ACTION_ITEM { name = "連環拳 十九、収勢", actioncode = "sports_renkanken_18" });
            ret.Add(new ACTION_ITEM { name = "怒りながら構えてポーズ", actioncode = "sports_riki_iri" });
            ret.Add(new ACTION_ITEM { name = "高速回転", actioncode = "sports_spin" });
            ret.Add(new ACTION_ITEM { name = "ヒンズースクワット", actioncode = "sports_squat" });
            ret.Add(new ACTION_ITEM { name = "マッスルオーケストラのポーズ", actioncode = "sports_strongman_orchestra" });
            ret.Add(new ACTION_ITEM { name = "ストロングマン　怒りの突進", actioncode = "sports_strongman_rush" });
            ret.Add(new ACTION_ITEM { name = "水面蹴り", actioncode = "sports_suimengeri" });
            ret.Add(new ACTION_ITEM { name = "シャイニングウィザード", actioncode = "sports_sw" });
            ret.Add(new ACTION_ITEM { name = "高橋大輔の４回転トゥループ", actioncode = "sports_takahashi_1440turn" });
            ret.Add(new ACTION_ITEM { name = "高橋大輔のキメポーズ", actioncode = "sports_takahashi_kime" });
            ret.Add(new ACTION_ITEM { name = "高橋大輔の情熱のステップ", actioncode = "sports_takahashi_step" });
            ret.Add(new ACTION_ITEM { name = "棚橋のエアギター", actioncode = "sports_tanahashi_guitar" });
            ret.Add(new ACTION_ITEM { name = "変身～宇宙キターッ！", actioncode = "sports_tvasahi_forze_kita_1208" });
            ret.Add(new ACTION_ITEM { name = "アクション仮面", actioncode = "sports_tvasahi_shinchan_wahaha" });
            ret.Add(new ACTION_ITEM { name = "ウィザード シャバドゥビタッチ変身", actioncode = "sports_tvasahi_wizard_shabadaba_1212" });
            ret.Add(new ACTION_ITEM { name = "後ろ受け身", actioncode = "sports_ukemi" });
            ret.Add(new ACTION_ITEM { name = "ハードなうさぎ跳び", actioncode = "sports_usagi_hard" });
            ret.Add(new ACTION_ITEM { name = "うさぎキック", actioncode = "sports_usagi_kick" });
            ret.Add(new ACTION_ITEM { name = "ソフトなうさぎ跳び", actioncode = "sports_usagi_soft" });
            ret.Add(new ACTION_ITEM { name = "レッドカード！", actioncode = "sports_wc_card_rd_1205" });
            ret.Add(new ACTION_ITEM { name = "イエローカード", actioncode = "sports_wc_card_yw_1205" });
            ret.Add(new ACTION_ITEM { name = "オフサイド！", actioncode = "sports_wc_offside_1205" });
            ret.Add(new ACTION_ITEM { name = "巨人が登場するときのアクション", actioncode = "super_titan_appear" });
            ret.Add(new ACTION_ITEM { name = "なにみてんのよ！この変体！（ビンタ", actioncode = "super_titan_attack_hand" });
            ret.Add(new ACTION_ITEM { name = "巨人アクション", actioncode = "super_titan_attack_smoke" });
            ret.Add(new ACTION_ITEM { name = "巨人ダメージフォール", actioncode = "super_titan_damage_fall" });
            ret.Add(new ACTION_ITEM { name = "落ちそうになる", actioncode = "super_titan_damage_fall_balance" });
            ret.Add(new ACTION_ITEM { name = "落ちそうになる", actioncode = "super_titan_damage_fall_click" });
            ret.Add(new ACTION_ITEM { name = "巨人ダメージ登る", actioncode = "super_titan_damage_fall_climb1" });
            ret.Add(new ACTION_ITEM { name = "落ちる", actioncode = "super_titan_damage_fall_repeat" });
            ret.Add(new ACTION_ITEM { name = "巨人ダメージラン", actioncode = "super_titan_damage_run" });
            ret.Add(new ACTION_ITEM { name = "姿を消す(すごく小さくなる)", actioncode = "super_titan_disappear" });
            ret.Add(new ACTION_ITEM { name = "姿を消す2", actioncode = "super_titan_disappear_titaneren" });
            ret.Add(new ACTION_ITEM { name = "巨人止まる", actioncode = "super_titan_stop" });
            ret.Add(new ACTION_ITEM { name = "巨人歩く", actioncode = "super_titan_walk" });
            ret.Add(new ACTION_ITEM { name = "上がる", actioncode = "swim_ashiari" });
            ret.Add(new ACTION_ITEM { name = "アップ", actioncode = "swim_ashiariUp" });
            ret.Add(new ACTION_ITEM { name = "足が埋まる", actioncode = "swim_long" });
            ret.Add(new ACTION_ITEM { name = "泳ぐ", actioncode = "swimaction" });
            ret.Add(new ACTION_ITEM { name = "足が消える", actioncode = "swimswim" });
            ret.Add(new ACTION_ITEM { name = "ジャンプ", actioncode = "syncarea" });
            ret.Add(new ACTION_ITEM { name = "おじぎ", actioncode = "thanks" });
            ret.Add(new ACTION_ITEM { name = "ようこそ VIPへ", actioncode = "thanks_vip" });
            ret.Add(new ACTION_ITEM { name = "おじぎからばいばい", actioncode = "thanksbyebye" });
            ret.Add(new ACTION_ITEM { name = "わっ！", actioncode = "trapjump_up" });
            ret.Add(new ACTION_ITEM { name = "２周年おめでとう", actioncode = "ufo_event_secret" });
            ret.Add(new ACTION_ITEM { name = "イベントセクシーダンス", actioncode = "ufo_eventdance_sexy" });
            ret.Add(new ACTION_ITEM { name = "クリスマス２０１５ダブルレフト", actioncode = "xmas2015_dance_double_left" });
            ret.Add(new ACTION_ITEM { name = "クリスマス２０１５ダブルライト", actioncode = "xmas2015_dance_double_right" });
            ret.Add(new ACTION_ITEM { name = "クリスマス２０１５ライトダウン", actioncode = "xmas2015_dance_lightdown" });
            ret.Add(new ACTION_ITEM { name = "クリスマス２０１５ダンス", actioncode = "xmas2015_dance_move" });
            ret.Add(new ACTION_ITEM { name = "クリスマス２０１５ダンスシングル", actioncode = "xmas2015_dance_single" });
            ret.Add(new ACTION_ITEM { name = "クリスマス２０１５ダンススリーグス", actioncode = "xmas2015_dance_three_gusu" });
            ret.Add(new ACTION_ITEM { name = "ウトウト", actioncode = "utouto_sit" });
            ret.Add(new ACTION_ITEM { name = "雛形1", actioncode = "template1", _adminAction = true });
            ret.Add(new ACTION_ITEM { name = "雛形2", actioncode = "template2", _adminAction = true });
            ret.Add(new ACTION_ITEM { name = "雛形3", actioncode = "template3", _adminAction = true });
            ret.Add(new ACTION_ITEM { name = "雛形4", actioncode = "template4", _adminAction = true });
            ret.Add(new ACTION_ITEM { name = "雛形5", actioncode = "template5", _adminAction = true });

            ACTION_ITEM[] items = ret.ToArray();

            return items;
        }

        public static List<ACTION_ITEM> getFilterACTION_ITEMCollection(string filterText)
        {
            List<ACTION_ITEM> ret = new List<ACTION_ITEM>();
            var data = getACTION_ITEMCollection();
            foreach (var item in data)
            {
                if (item.name.Contains(filterText) | item.actioncode.Contains(filterText))
                {
                    ret.Add(item);
                }
            }
            return ret;
        }

    }
    public class ACTION_ITEM
    {
        public string name;
        public string actioncode;
        public bool _adminAction = false;
    }
}