//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace craxx_plus.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("craxx_plus.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAO3xbOtYH7kCaO0XuQJ1fAwAAAAACAAAAAAAQZgAAAAEAACAAAAAghtoOgFNXz1/cvlrGiLQRig9afOZ5GmA7/uG5XnrTQQAAAAAOgAAAAAIAACAAAAAVGJDzBQBBwoIg0besU9gt6uiu2fRNH3L6RJaPbNWsHGCHAgCePXs4HIb8oLNy4T2Mo8GfcgsUDFXWpLZLlj1KXoxQRawAZIeuwLx3WLixkxRtdwx8OIQRHj9JUECrKXY5jHGkvOCFN45IxXD76o9LmlC5pg35sHgNB63QYNlI3oTWajkr8E8F1MIOCRwrxTAKrDuJ/TASs+MyUl7E4yYULcfvf3tZtsjpIxi7PEumPXoakVFRsSHzC0VMMtmclaTlBBGN/xoEMB5S4ZFygJzHM+HGrP8GHeRn9r6n0O7SUsLWSr9kCGxdrneKmOLYhOPIcR6Ks9DMgdIoMiTr/U0cQRDgbbQheBIpIhpk1NI0Etut [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string crypted_array {
            get {
                return ResourceManager.GetString("crypted_array", resourceCulture);
            }
        }
    }
}
